### ISSUE TITLE
API to start Pause / Play Animation

### ISSUE THREAD

**Issue by kevkha** [jaruba/wcjs-player#10]
Can the toolbar be reused outside of the player div? Just don't want to reinvent the wheels since all of the CSS and jquery codes are there especially the removeClass and addClass for the icons.

**Comment by jaruba** [comment]
> Can the toolbar be reused outside of the player div?

Can you please elaborate, not sure I understand.

**Comment by kevkha** [comment]
Sorry about that :) I want to reuse some of the control buttons inside <code>wcp-toolbar</code> div. The prev, play/pause, next buttons etc...

**Comment by jaruba** [comment]
unfortunately not, everything is strongly linked together, looking in the code should help you make everything a lot faster though..

**Comment by kevkha** [comment]
Yes, I did and a lot of works :) I am able to create functions and toggle icons again but would like to see the animated icons for Play and Pause on the main player too when I click the buttons outside of the player div.

**Comment by jaruba** [comment]
oh, that's easy to do, I will add a function for that and release it in a couple of minutes

**Comment by kevkha** [comment]
That's very nice of you. Looking forward to it. Thanks.

**Comment by jaruba** [comment]
Published ``wcjs-player`` v0.4.4, it has a ``.animatePause()`` function that can be used along with ``.play()`` , ``.pause()`` and ``.togglePause()``.

Example usage:

    player.play().animatePause();
    player.pause().animatePause();
    player.togglePause().animatePause();

please test it.

**Comment by jaruba** [comment]
make sure to backup your changed css file before updating, and after updating add your old ``general.css`` over the new one, to keep your changes.

**Comment by jaruba** [comment]
Also, as an alternative solution to this, and maybe your first question too, you can activate any button by their CSS classes.

Examples:

    player.wrapper.find(".wcp-pause").trigger("click");
    player.wrapper.find(".wcp-play").trigger("click");
    player.wrapper.find(".wcp-maximize").trigger("click");
    player.wrapper.find(".wcp-minimize").trigger("click");
    player.wrapper.find(".wcp-playlist-but").trigger("click");
    player.wrapper.find(".wcp-subtitle-but").trigger("click");

**Comment by kevkha** [comment]
I tested all of the above and they work great! Many thanks!
Could you please add API to display logo when playlist is empty and player.stop() is trigger?

**Comment by jaruba** [comment]
Do you mean WebChimera's logo or your custom logo?

**Comment by kevkha** [comment]
For custom logo. Option to define logo path would be nice too. Thanks.

**Comment by jaruba** [comment]
I don't think it's a good ideea to give the option for a custom logo.

Branding presumes ownership, if it should be done then it should be for WebChimera, it's the most basic type of marketing available and the only one that is free for us, it ensures WebChimera can grow and it needs this heavily considering ``WebChimera.js`` is still very very new.

There are many ways to brand a nw.js / electron app, the player does not need to be branded with the app logo, recognition should be given for the team at WebChimera.

**Comment by kevkha** [comment]
Understandable.I will implement app logo instead. Let's close this issue. Thanks again.
