### ISSUE TITLE
Switching to relative paths broke up electron

### ISSUE THREAD

**Issue by vintikzzz** [jaruba/wcjs-player#14]
In a commit number cd4f302e7ff81c7654bcdf4dc7f6f37cb420ed82 there was a switch to relative paths for css and image files. Electron can't find any of them after that. Any work around?
Version 0.4.4 works fine!

**Comment by jaruba** [comment]
could you please open up a dev console and write:

    var path = require('path');
    var relbase = path.relative(path.dirname(require.main.filename), __dirname);
    relbase

**Comment by jaruba** [comment]
also, please mention what OS you are on.

**Comment by jaruba** [comment]
I just released ``WebChimera.js Player v0.4.9`` that has [**THE FIX**](https://github.com/jaruba/wcjs-player/commit/67a33c965fc82527f069f32de622f6f5c561b1e7) (pretty funny fix, lol)

I tested it in ``NW.js`` and ``Electron`` on Windows, please try it and see if it works for you too. :)

**Comment by vintikzzz** [comment]
Wow! Wow! It really works again!
Thank you!
I am using Mac OS X.

**Comment by jaruba** [comment]
Great! Now I know it works on OS X too.

Thank you for the reporting this! :)
