### ISSUE TITLE
Select a subtitle on load

### ISSUE THREAD

**Issue by siuying** [jaruba/wcjs-player#15]
Can I set subtitles programmatically? This is how I add subtitle:

```javascript
var params = {url: "the-url", subtitles: {"English": "subs-url"}}
var player = new wjs("#player").addPlayer({ autoplay: true });
player.addPlaylist(params)
```

However, this would only add the subtitles to video, not activate them. User would have to manually select the subs from menu. 

Adding ``subTrack()`` do not seems help (it would work if the video is loaded and i run it in console)

```javascript
player.subTrack(1)
```

**Comment by jaruba** [comment]
var params = {url: "the-url", subtitles: {"English": "subs-url"}}
    var player = new wjs("#player").addPlayer({ autoplay: true });
    player.onPlaying(function() {
        player.subTrack(1);
    });
    player.addPlaylist(params)

**Comment by siuying** [comment]
Thanks! that's what I needed.

**Comment by jaruba** [comment]
make sure you use the latest example code i posted in the comment (i changed it a few times), also there might be better ways to do it, this is just the first way I thought of..

**Comment by siuying** [comment]
👍
