### ISSUE TITLE
not a valid Win32 application

### ISSUE THREAD

**Issue by avrandrei** [jaruba/wcjs-player#16]
Hi! I'm trying to run the example app with Electron under Windows 8 (x64) and keep getting the %1 is not a valid Win32 application error.

I'm pretty new to this. Could you please advise?

Thanks

**Comment by jaruba** [comment]
`WebChimera.js` builds for 32bit by default, so please use Electron 32bit instead of 64bit.

**Comment by anavram** [comment]
Thank you! That fixed my problem!

**Comment by jaruba** [comment]
Great :)
