### ISSUE TITLE
Disable user action on video

### ISSUE THREAD

**Issue by mpastell** [jaruba/wcjs-player#17]
It would good if nice if you could disable user input from video. I'm working on behavioral coding software (https://github.com/mpastell/CowLog) that can play multiple videos simultaneously and I don't want the users to accidentally interact with the videos.

I solved the problem for now by using a custom version of wcjs-player with surface click actions and pointer cursor on videos removed.

Thanks for a very useful project!

**Comment by jaruba** [comment]
> disable user input from video

do you mean to disable the ``.togglePause()`` from the canvas click event?

or all user input? (no toolbar either)

**Comment by mpastell** [comment]
For my purpose all user events and the toolbar. I removed the fullscreen option and pause for now.

**Comment by jaruba** [comment]
so you don't need the fullscreen feature at all?

**Comment by mpastell** [comment]
In this case no.

By the way, I'm going to add links to your project on the website and repo as soon as it is included in the released version.

**Comment by jaruba** [comment]
Check out this black magic one liner that does exactly what you want (with multiscreen set to `true`):

    player.find(".wcp-surface").unbind("click").unbind("dblclick").css("cursor","default","important");

Full HTML example (based on the [node-vlc-multiscreen](https://github.com/jaruba/node-vlc-multiscreen) example):

    <html>
        <head>
            <style>
                body,html{
                    width: 100%;
                    height: 100%;
                    padding: 0px;
                    margin:0px
                }
                .webchimeras {
                    float: left;
                    width: 50%;
                    height: 50%
                }
            </style>
        </head>
        <body>
            <div id="player"></div>
            <div id="player2"></div>
            <div id="player3"></div>
            <div id="player4"></div>
            <script>
            var wjs = require("wcjs-player");
            
            var player = new wjs("#player").addPlayer({ multiscreen: true, autoplay: true, loop: true });
            
            player.addPlaylist({
                url: "http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4",
                crop: "16:9"
            });
            
            player.find(".wcp-surface").unbind("click").unbind("dblclick").css("cursor","default","important");
            
            player2 = new wjs("#player2").addPlayer({ multiscreen: true, autoplay: true, loop: true });
            player2.addPlaylist({
                url: "http://archive.org/download/CrayonDragonAnAnimatedShortFilmByTonikoPantoja/Crayon%20Dragon%20-%20An%20animated%20short%20film%20by%20Toniko%20Pantoja.mp4",
                crop: "16:9"
            });
            
            player2.find(".wcp-surface").unbind("click").unbind("dblclick").css("cursor","default","important");
            
            player3 = new wjs("#player3").addPlayer({ multiscreen: true, autoplay: true, loop: true });
            player3.addPlaylist({
                url: "http://archive.org/download/CartoonClassics/Mel-O-Toons__Peter_and_the_Wolf.mp4",
                crop: "16:9"
            });
            
            player3.find(".wcp-surface").unbind("click").unbind("dblclick").css("cursor","default","important");
            
            player4 = new wjs("#player4").addPlayer({ multiscreen: true, autoplay: true, loop: true });
            player4.addPlaylist({
                url: "http://archive.org/download/popeye_patriotic_popeye/popeye_patriotic_popeye.ogv",
                crop: "16:9"
            });
            
            player4.find(".wcp-surface").unbind("click").unbind("dblclick").css("cursor","default","important");
            
            </script>
        </body>
    </html>

> By the way, I'm going to add links to your project on the website and repo as soon as it is included in the released version.

Awesome! :)

**Comment by mpastell** [comment]
Excellent, thanks for the very quick response!

**Comment by jaruba** [comment]
I'll make a PR :)

**Comment by jaruba** [comment]
Done! https://github.com/mpastell/CowLog/pull/2
