### ISSUE TITLE
How to overlay content on top of wcjs-player in fullscreen mode?

### ISSUE THREAD

**Issue by oaprograms** [jaruba/wcjs-player#18]
I made some custom, absolute-positioned content (divs and buttons) on top of wcjs-player (on sibling div with higher z-index value). However, they disappear on fullscreen mode. What is the easiest way to circumvent this? Putting them inside #player div doesn't seem to work. Is there perhaps a way to disable default full screen behavior, and replace it with custom one, that makes entire app window go fullscreen?

Thanks

**Comment by jaruba** [comment]
If you did:

    var player = new wjs("#player").addPlayer({ autoplay: true });

Then the player creates this HTML code:

    <div id="player_wrapper" class="webchimeras">
        <div id="webchimera" class="wcp-wrapper">
            ...
        </div>
    </div>

and `#webchimera` is the DOM node that is sent into fullscreen mode.

Overwriting the fullscreen functionality from outside the code is theoretically possible but not recommended, as it does more then just request html5 fullscreen (also changes some CSS of other DOM nodes for fullscreen mode), and not only the toolbar button requests fullscreen (double clicking the video also does the same thing).

My suggestion is to append your custom code to `#webchimera` by doing:

    player.wrapper.append('<div>My cool new DOM node</div>');

it might not be easy to position it easily though, but certainly doable with CSS.

Something to note is that `player.wrapper` returns a jQuery object of the `.wcp-wrapper` element, so it supports all jQuery methods. :)
