### ISSUE TITLE
hotkeys

### ISSUE THREAD

**Issue by alex-rokabilis** [jaruba/wcjs-player#19]
Hello,
Does wcjs-player support hotkeys like the plugin?

**Comment by jaruba** [comment]
Unfortunately, no, as it's all made in JS I wanted to give more control for developers to make their own hotkeys and solutions for their specific needs. The JS API is very advanced and can handle making any sort of hotkey or button for any particular need. (I also didn't make a context menu for the same reason)

However, I have made many different branches/clones of `wjcs-player` in this time, that are customized and optimized for specific tasks/requirements. In one such clone (`pw-wcjs-player`, that was made entirely for [Powder Player](https://github.com/jaruba/PowderPlayer)) I did implement hotkeys. I used the [hotkeys](https://www.npmjs.com/package/hotkeys) module, and the entire list of hotkeys I made for it can be found here: https://github.com/jaruba/PowderPlayer/wiki/Hotkeys

The implementation itself:

https://github.com/jaruba/pw-wcjs-player/blob/master/index.js#L38
https://github.com/jaruba/pw-wcjs-player/blob/master/index.js#L833
https://github.com/jaruba/pw-wcjs-player/blob/master/index.js#L2774-L3118

This should be easily customizable for any situation, and does not need to be necessarily integrated in the player itself (it can be easily added outside of `wcjs-player` with the exact same effect).

I will, although, leave this question open for a period of time. If other users will `+1` this, then there is a real need for it and I will add it to the repo.

**Comment by jaruba** [comment]
I think this has been open for long enough, I also don't think it's a good idea to have hotkeys in a node.js module.

Maybe those hotkeys are already mapped to something else that is needed in the apps that include this.

It's easy enough to make hotkeys for anything with the player js api and the best way to do it is to listen to the hotkeys on the window object, not the player dom element.
