### ISSUE TITLE
nwjs instructions

### ISSUE THREAD

**Issue by smolleyes** [jaruba/wcjs-player#23]
hello jaruba :)

i think you might add some doc to init the player for nwjs

you exemple is right with electron but not nwjs

when i try it now i have error

"Uncaught TypeError: Cannot read property 'firstChild' of null", source: /home/sylvain/Documents/projets/git/StreamStudio/node_modules/wcjs-player/index.js (75)

and are we forced to use the app:// protocol first (same error with it)

thanks

**Comment by smolleyes** [comment]
in another app where i use koajs as main framework and another way to init the app the player loads fine but when i open a 3d movie, it play fine then when i forward in the stream it s not buffering and the app is freezed :)

++

**Comment by jaruba** [comment]
omaggawd, it's smolleyes!

**Comment by jaruba** [comment]
want me to invite you to Magics (Slack chat)? It's where all the cool people hang out and we can keep in touch easier, just need to give me your email. :)

**Comment by jaruba** [comment]
As for your questions, how are you initiating your player?

In the example I recommend:
```
var player = new wjs("#player").addPlayer({ autoplay: true });
```

On line 75 (where the error is) it says:
```
    if (this.context.substring(0,1) == "#") {
        if (window.document.getElementById(this.context.substring(1)).firstChild) {
```

If you initiated the player in the recommended way, then it should translate to:
```
window.document.getElementById("player").firstChild
```

So the question is, what do you get in the console log when doing:
```
window.document.getElementById("player")
```
(in the case you called `wjs("#player")`)

**Comment by smolleyes** [comment]
lol :) i m baaaaaaackk :p

s.laguiatgmail.com

**Comment by jaruba** [comment]
invited and spoofed email :))

**Comment by smolleyes** [comment]
i have no mails :p

**Comment by jaruba** [comment]
s.laguiat@gmail.com , right?

**Comment by smolleyes** [comment]
lol no at = @

**Comment by jaruba** [comment]
rofl

**Comment by smolleyes** [comment]
:dancer:

**Comment by jaruba** [comment]
sent again :))

**Comment by smolleyes** [comment]
ok i m in, then ?

**Comment by jaruba** [comment]
Get accustomed with the madness in there. :))

There's a lot of people that can make your journey easier.

**Comment by jaruba** [comment]
i think this was solved already in a private chat
