### ISSUE TITLE
Module version mismatch. Expected 14, got 43

### ISSUE THREAD

**Issue by creativefull** [jaruba/wcjs-player#24]
![image](https://cloud.githubusercontent.com/assets/13174684/11536048/641989de-9949-11e5-9f8a-fd1411cf376d.png)

after i build get Error that this :( help me

**Comment by RSATom** [comment]
what command did you use to build it?

**Comment by creativefull** [comment]
i use it https://github.com/Gisto/nwjs-shell-builder

**Comment by creativefull** [comment]
ok it's fine, I use version 0.12.3 nwjs .

:) sorry for my issue :+1:
