### ISSUE TITLE
Compiled App Crashed when playing video

### ISSUE THREAD

**Issue by creativefull** [jaruba/wcjs-player#25]
i'm executing using shell :$ ./myapp

the app works until i played the video , then it crashed. (closed unexpectedly)

```
[3791:1203/174251:WARNING:crash_handler_host_linux.cc(289)] Could not translate tid - assuming crashing thread is thread group leader; syscall_supported=1
```

FYI it works fine before packaging. (by using npm start. )
I'm Using Arch Linux

**Comment by jaruba** [comment]
Arch Linux? Are you using this on an ARM device?

**Comment by creativefull** [comment]
Linux muzaki 4.2.5-1-ARCH #1 SMP PREEMPT Tue Oct 27 08:13:28 CET 2015 x86_64 GNU/Linux

**Comment by RSATom** [comment]
@creativefull, could you please try https://github.com/RSATom/wcjs-ugly-demo ?

I think you use wrong .node file (maybe built for different engine or engine version)

**Comment by creativefull** [comment]
@RSATom OK thanks i'll try again :)
