### ISSUE TITLE
print timer for live streams ?

### ISSUE THREAD

**Issue by smolleyes** [jaruba/wcjs-player#27]
hello

if i load a tv stream from my tv box the player do not show any timer...

is it possible to write "live stream" or something ? 

look my post here :)

https://github.com/RSATom/WebChimera.js/issues/57#

thanks

**Comment by jaruba** [comment]
uhm, i need a live stream link to test with

**Comment by jaruba** [comment]
I tested a live stream and checked the code, there isn't any sort of limitation for live streams. Their handled the same way as any other video and will print the time if it is received from `wcjs`.

In my tests, althought the `onTime` event was triggered, the time that was passed was always `0`. I'm pretty confident that the current time simply isn't available for some live streams.
