### ISSUE TITLE
Error When Change Page

### ISSUE THREAD

**Issue by creativefull** [jaruba/wcjs-player#29]
Hi @jaruba when i open player on new window i get error like this
```
Uncaught TypeError: Cannot read property 'firstChild' of null
```
but when i reload window i did'nt get error ,
do you have solutions ?

**Comment by jaruba** [comment]
What are you using? Electron or NW.js? Are you also using some templating system? Such as AngularJS or React?

**Comment by creativefull** [comment]
i'm using NW.js with angular

**Comment by jaruba** [comment]
It might be useful for you to read this: https://github.com/jaruba/wcjs-player/issues/6

Seems to be the same issue.

**Comment by creativefull** [comment]
i get error when i use this script

```
var gui = require('nw.gui');
gui.Window.open('player.html');
```
then i get error like thats

**Comment by jaruba** [comment]
Are you loading `wcjs-player` after the window has fully loaded?

Example from the linked issues ( https://github.com/jaruba/wcjs-player/issues/6 ):
```
window.onload = function() {
    player = new wjs("#player").addPlayer({ autoplay: true });
    player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
};
```

**Comment by creativefull** [comment]
wait i'll try again

**Comment by creativefull** [comment]
![screenshot at 2015-12-23 21 02 01](https://cloud.githubusercontent.com/assets/13174684/11977797/978804d8-a9b8-11e5-8f35-92b2a022e1f8.png)

error :'(

**Comment by jaruba** [comment]
It is abundantly clear to me that the very first time you call `new wjs` on the page, the page has not yet completed loading the dom. I bet that if you do something like:

```
window.onload = function() {
    setTimeout(function() {
        player = new wjs("#player").addPlayer({ autoplay: true });
        player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
    },1000);
};
```

then it will work, but the question is why the dom isn't loaded until the window is loaded.

**Comment by creativefull** [comment]
still error :'(

**Comment by jaruba** [comment]
Well.. I have no idea why it may do this... So I'm just gonna start hacking at it, with your initial code, do this:

When you open the new window:
```
var gui = require('nw.gui');
localStorage.miaw = '0';
gui.Window.open('player.html');
```

In the new window:
```
window.onload = function() {
    if (localStorage.miaw == '0') {
        localStorage.miaw = '1';
        var gui = require('nw.gui');
        var win = gui.Window.get();
        win.reload();
    }
}
```

:)))

**Comment by creativefull** [comment]
if use that code ,. how i can get window opener (parent window) ?

**Comment by jaruba** [comment]
why would it loose the reference to parent window? it's just reloading the page, the parent reference shouldn't be changed.. (i think/hope)

why would you need the parent window though? for cross-window communication i usually use websockets. In which case I open the new window with an anchor, such as `player.html#4545` where `4545` is the websocket server port (that i parse from the currently loaded window link), then just establish the websocket connection and pass objects back and forth through it.

**Comment by jaruba** [comment]
you could even put the websocket logic in the else clause of the code above, like:

```
window.onload = function() {
    if (localStorage.miaw == '0') {
        localStorage.miaw = '1';
        var gui = require('nw.gui');
        var win = gui.Window.get();
        win.reload();
    } else {
        // connect to websocket server here
    }
}
```

So it only connects after the reload.

**Comment by creativefull** [comment]
I do not understand what the problem is ,
I keep getting an error :sob:

**Comment by jaruba** [comment]
what are the chances that you can make a very simple demo app that reproduces the error? Without having an environment in which i can test this situation, it's pretty hard to think of more solutions. :(

**Comment by creativefull** [comment]
Okeh i'll create simple demo app ..

**Comment by creativefull** [comment]
https://www.dropbox.com/s/bkn1xflgojd82ms/demo-wcjs.zip?dl=0 =======> this sample

**Comment by jaruba** [comment]
With your demo, I'm getting:

> Uncaught TypeError: Cannot read property 'addRule' of undefined

not:

> Uncaught TypeError: Cannot read property 'firstChild' of null

**Comment by creativefull** [comment]
yes it is, there are two possible errors that often appear
sorry because i'm using other demo :v: :smiley:

**Comment by creativefull** [comment]
OK, i have been get solution , :smile: 
because i'm using angular , so i load first dom and i scope dom :+1: 
it's fix

**Comment by jaruba** [comment]
It's strange though, I was just about to blame NW.js for a pretty bad bug.

In the example you sent me, your requiring `wcjs-player` for the first time in a new window, but it's being loaded in the parent window and only the object reference is passed down to the child window. But the player needs to inject it's dom nodes and css to work, and it can't do that when being loaded in a different window.

I'm actually amazed that it works with your angular app.. :santa:

**Comment by xo1988** [comment]
do you have demo about using gui.Window.open('child.html'), and then link the div in child html to play video?

**Comment by jaruba** [comment]
For others that might reach this page looking for a solution to using `NW.js` with `wcjs-player` in a second window, we now have [a hack](https://github.com/jaruba/wcjs-player/issues/44#issuecomment-198853189) for it.
