### ISSUE TITLE
Player events not working

### ISSUE THREAD

**Issue by sammuel86** [jaruba/wcjs-player#3]
when using sampe code provided at: https://github.com/jaruba/wcjs-player/wiki/Code-Examples

all the event code throws errors saying the functions are undefined. Any fix for this?

![](http://i.imgur.com/rQP8c8H.png)

**Comment by jaruba** [comment]
I can't believe you made a screenshot then even took the time to crop it just for this silly little error. :)

Please check ``/node_modules/wcjs-player/index.js`` on line 19 and make sure you have ``WebChimera.js Player v0.2.7`` installed:

https://github.com/jaruba/wcjs-player/blob/master/index.js#L19

**Comment by jaruba** [comment]
Scratch that, the issue is that your not initializing the player correctly. Change this line:

    var player = wjs("#mainPlayer");

to this line:

    var player = new wjs("#mainPlayer").addPlayer();

**Comment by jaruba** [comment]
I've done some more tests on this, even if you previously initialized the player in order to recall the API you would still need to use ``new``.

So in your case it should just be:

    var player = new wjs("#mainPlayer");
