### ISSUE TITLE
$.extend

### ISSUE THREAD

**Issue by marcuzy** [jaruba/wcjs-player#30]
I try use wcjs-player and get this error. The error appeared after "const wcjs = require("wcjs-player");" What is wrong? (I using Electron)

App threw an error when running [TypeError: $.extend is not a function]
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: $.extend is not a function
    at /home/marcuzy/el-app/node_modules/jquery-ui/core.js:21:3
    at Object.<anonymous> (/home/marcuzy/el-app/node_modules/jquery-ui/core.js:322:3)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (module.js:385:17)
    at Object.<anonymous> (/home/marcuzy/el-app/node_modules/jquery-ui/sortable.js:2:1)
    at Module._compile (module.js:425:26)

**Comment by jaruba** [comment]
`(/home/marcuzy/el-app/node_modules/jquery-ui/core.js:322:3`

you have `jquery-ui` included in your app, the player also has it, it's loading your app's `jquery-ui` instead of it's own.

**Comment by jaruba** [comment]
try including this `jquery-ui` instead of the one you are now in your `package.json`:

```
        "jquery-ui": "jaruba/jquery-ui",
```

**Comment by jaruba** [comment]
this topic has been inactive for too long, if you still have issues please reopen it

**Comment by mattholmes** [comment]
Im having the same problem but i am already using the jaruba/jquery-ui package not the default

**Comment by jaruba** [comment]
@mattholmes 
try removing all modules from your npm cache and doing `npm install wcjs-player` again

**Comment by mattholmes** [comment]
i got the same issue, i have just realised that i was using the wcjs-prebuilt package that apparently isnt supported, ill try get it working without wcjs-prebuilt

**Comment by jaruba** [comment]
that shouldn't be the reason, also, it does support `wcjs-prebuilt` with a fallback parameter, see this comment:
https://github.com/jaruba/wcjs-player/issues/33#issuecomment-180796556

**Comment by jaruba** [comment]
If the npm cache is not the reason here, I can't imagine what is, I've used `wcjs-player` numerous time without any such error.. you could try changing `package.json` with the latest `jquery-ui` instead of my fork, maybe they fixed the issues I had with it.

**Comment by mattholmes** [comment]
ill give it a go with wcjs-prebuilt and the latest jq-ui later on today and report back, thanks

**Comment by mattholmes** [comment]
i ended up starting a new project, importing all the modules again then just copying over my original project files and now its up and working (using the latest version of jquery-ui) thanks for your help

**Comment by jaruba** [comment]
@mattholmes interesting, I'll test out the latest jq-ui, if it works for me too, maybe i'll be able to finally get rid of that damned fork :)

thank you for reporting your findings

**Comment by spookssi** [comment]
Hi @jaruba , i have the same error.
-Electron 0.37.8
-MAC OS X

`    Uncaught Exception:
TypeError: $.extend is not a function
    at /Users/utilisateur/Desktop/Peris/dist/osx/PeriIntime-darwin-x64/PeriIntime.app/Contents/Resources/app/node_modules/jquery-ui/core.js:21:3
    at Object.<anonymous> (/Users/utilisateur/Desktop/Peris/dist/osx/PeriIntime-darwin-x64/PeriIntime.app/Contents/Resources/app/node_modules/jquery-ui/core.js:322:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/utilisateur/Desktop/Peris/dist/osx/PeriIntime-darwin-x64/PeriIntime.app/Contents/Resources/app/node_modules/jquery-ui/sortable.js:2:1)
    at Module._compile (module.js:413:34)`

When i run my App with npm start no error - 0 problem but after electron-packager build i can't open the app...

I deleted wcjs-player/node_module/jquery-ui to let myApp/node_module/jquery-ui be the only one jquery-ui module but the error stay ( not a the same emplacement lol but dont disapear).

Do you have a solution ? :)
Thank.

**Comment by jaruba** [comment]
@spookssi i can't be sure what `electron-packager` does.. Does it flatten the `node_modules` folder? Does it create an `asar` file?

**Comment by spookssi** [comment]
I dont know how to check if the packager create an asar files. I dont know if the node_modules is flattened, how can i see this ?

The electron app doesnt work too with electron(terminal and app ). Just work with npm start...
`[TypeError: $.extend is not a function]`

**Comment by jacopocarlini** [comment]
I have same problem.

**Comment by gslopez** [comment]
I have same problem.
