### ISSUE TITLE
Show subtitle onPaused only

### ISSUE THREAD

**Issue by alta0815** [jaruba/wcjs-player#41]
Can I show subtitle onPaused only, when onPlayed hide it?
That\`s how I do now: 

	var wjs = require("wcjs-player");
	var player = new wjs("#player").addPlayer({ mute: true });
	var src = "file:///" + "C:/Users/un1acker/Desktop/sample" + "/spartac.mkv";
	var sub = "C:/Users/un1acker/Desktop/sample" + "/spartac.srt";

	player.addPlaylist({
		url: src
    });
	player.play();

	player.onPlaying(function() {
		//subtitle none
	    player.subTrack(0);
	});

	player.onPaused(function() {
		//english subtitle
		player.subTrack(3);
	});

But it`s not activate subtitle.

**Comment by jaruba** [comment]
Subtitles are closely linked to the `.onTime()` event.

`.subTrack()` only selects/deselects them, but `.onTime()` makes them show.

As `.onTime()` triggers only during playback, subtitles won't show if selected while being in the paused state.

**Comment by alta0815** [comment]
Thanks for answering)

**Comment by jaruba** [comment]
I'm sorry I couldn't be of more help.. but I really can't see any way to do it..
