### ISSUE TITLE
error versions on windows and electron 0.37.2

### ISSUE THREAD

**Issue by Nicoss** [jaruba/wcjs-player#42]
hi.
I tryed a lot to make the wcjs works but i'm still stuck when i call addPlay().
I tryed add wcjs player to my project and have a runtime javascript error in console. I tryed a lot of configuration with VLC win.32 or 64, electron with ia32 or 64, even with node 32 and 64bit and still have error.

If i launch application with the x64 version of electron got
> Error: %1 is not a valid Win32 application.

and if i launch application with the ia32 version of electron got 
> Error: The specified module could not be found.

I got all prerequesites having a full generation with no error or warning when i install wcjs-player
I tryed using the prebuilt here https://github.com/Ivshti/wcjs-prebuilt and then install wcjs-player and now i'm stuck with this message
> Error: Module version mismatch. Expected 47, got 46.

can't install wcjs-player. Is it a know issue, do you a fix or a way to help me ?

Thanks

**Comment by RSATom** [comment]
I recommend you start from https://github.com/RSATom/wcjs-ugly-demo and only when you will get it working, try something more complex.

**Comment by jaruba** [comment]
But, can the prebuilt even handle electron 0.37.2?

I agree with @RSATom , you should install the pre-requisites and use `wcjs-ugly-demo` to build `webchimera.js` for your electron version and architecture.

```
set npm_config_wcjs_runtime="electron"
set npm_config_wcjs_runtime_version="0.37.2"
set npm_config_wcjs_arch="x64"

npm install
```
(arch can be x64 or ia32)

I think that for Electron 0.36+ you'll also need to set an env var before loading the renderer window:

```
if(process.platform == 'win32')
    process.env['VLC_PLUGIN_PATH'] = path.join(__dirname, 'node_modules/webchimera.js/plugins')
```

Keep in mind that Electron, WebChimera.js and VLC need to all be the same architecture in order for it to work.

**Comment by RSATom** [comment]
> But, can the prebuilt even handle electron 0.37.2?

https://github.com/RSATom/WebChimera.js/releases has only prebuilt for v0.36.7

**Comment by RSATom** [comment]
`Electron` release too quickly - 4 different version within 3 days...

**Comment by jaruba** [comment]
Yeah, it's impossible to keep up with them, and everyone seems willing to use the bleeding edge versions.

I don't understand why though, I'm still on Electron 0.33.9 and I see no issues with it..

**Comment by Nicoss** [comment]
well the version of electron is because your prebuilt check latest version. wich is 0.37.2
I tryed a lot using different versions. I keep trying installing the ugly-demo with no success.

**Comment by jaruba** [comment]
If you want you can start a team viewer and send me the login details on my email (available on my github profile) or i can try to build `webchimera.js` for you..

I'm not sure what more I can say then I already said in the previous comment..

**Comment by jaruba** [comment]
If I wore to guess.. I'd say you didn't add VLC to the `/node_modules/webchimera.js/build/Release/` folder.

**Comment by Nicoss** [comment]
I did.

The only thing I can say is that I had the same issue when I tryed with nw.js and problem fixed using the ia32 version of nw.js. But when i try with the ia32 version of electron, have issues too

**Comment by RSATom** [comment]
@Nicoss, what error did you get with Electron last time?

**Comment by jaruba** [comment]
> Uncaught Error: %1 is not a valid Win32 application. *\wcjs-ugly-demo\node_modules\webchimera.js\build\Release\WebChimera.js.node

**Comment by RSATom** [comment]
it's mixing x64/ia32 modules

**Comment by jaruba** [comment]
http://webchimera.org/samples/wcjs-electron-0.37.2.zip

**How did i do it?** Simple, I did **exactly** what I wrote in my first comment:

**1**. Made sure I had all the [WebChimera.js Build Prerequisites](https://github.com/RSATom/WebChimera.js#build-prerequisites) installed on my computer

**2**. Download `wcjs-ugly-demo`: https://github.com/RSATom/wcjs-ugly-demo/archive/master.zip

**3**. Edited `build_electron.cmd` and changed it to:

```
set npm_config_wcjs_runtime="electron"
set npm_config_wcjs_runtime_version="0.37.2"
set npm_config_wcjs_arch="ia32"
npm install
```

**4**. Opened a command line and executed `build_electron.cmd`

**5**. Downloaded `Electron v0.37.2 ia32` for Windows: https://github.com/atom/electron/releases/download/v0.37.2/electron-v0.37.2-win32-ia32.zip

**6**. Unpacked Electron in the same folder as `wcjs-ugly-demo`

**7**. Downloaded `VLC v2.2.2 ia32` for Windows:
http://download.videolan.org/pub/videolan/vlc/2.2.2/win32/vlc-2.2.2-win32.zip

**8**. Unpacked VLC in the same folder as `webchimera.js.node` (which is `node_modules/webchimera.js/build/Release/`)

**9**. Edited `electron_main.js` and added this as the first line:

```
process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, 'node_modules/webchimera.js/build/Release/plugins')
```

**10**. Opened a command line and executed `run_electron.cmd`
