### ISSUE TITLE
Crashes by calling chimera_player.next() or chimera_player.removeItem() while on onPlaying() event

### ISSUE THREAD

**Issue by Chayemor** [jaruba/wcjs-player#43]
**Environment**

- NW.js v0.12.3 (32 bits)
- io.js v1.2.0 (32 bits)
- Windows 8
- Webchimera.js (player)
- [VLC Build (2.2.1)](http://www.videolan.org/vlc/download-windows.html)

**Requirement**: Get video length of playlist items.

Following code causes crash without any error messages.

```
wjs = require('wcjs-player');

...
chimera_container = new wjs("#chimera_container");
chimera_player = chimera_container.addPlayer({ mute: true, autoplay: false, titleBar: "none" }); 
chimera_player.onPlaying( OnPlaying ); // Extracts length information
...
var OnPlaying = function(){
    chimera_player.pause(); // Doesn't seem to pause it, state stays "playing"
    console.log( chimera_player.itemDesc(chimera_player.currentItem()).mrl , chimera_player.length());
    // It works up to here. Following instruction causes crash.
   //  chimera_player.removeItem(X) causes crash as well.
    if(!chimera_player.next())
        chimera_player.clearPlaylist();
 };
```

My temporary fix was to call `chimera_player.pause()` on **onPlaying** and then on **onPaused** carry out the code of information extraction. That worked fine. I [wrote ](http://stackoverflow.com/questions/36017000/video-length-of-playlist-items-webchimera-js-player?stw=2)about it on Stackoverflow, was asked to create an issue for it here.

ps: thanks for WebChimera.js (player), quite sweet.

**Comment by jaruba** [comment]
What VLC build are you using and where are you getting it from?

**Comment by RSATom** [comment]
@Chayemor, thank you for report. I'll check.

**Comment by RSATom** [comment]
@jaruba, initial conversation: http://stackoverflow.com/questions/36017000/video-length-of-playlist-items-webchimera-js-player/36027251

**Comment by jaruba** [comment]
@RSATom My question is still valid, I want to know where he's getting his VLC build from and what version it is, some of his questions sound related to a broken VLC build.

I'm not entirely sure how `libvlc_media_get_duration`, but I have a feeling it uses `ffprobe` to get the duration, which makes me think that it will only work for local files, and not network media.

Does pausing work if you use it with a 1 second timeout?

```
var OnPlaying = function(){
    setTimeout(function() {
        chimera_player.pause();
    }, 1000);
    ...
```

I know for a fact that volume control, pause and play are ignored during the buffering / opening states, maybe next / prev are ignored too, but this has always been the default behavior of VLC.

To get the length of the currently running media, it's best to listen to this event:
```
player.vlc.onLengthChanged(function(length) {
    console.log('my video length is: ' + length);
});
```

**Comment by Chayemor** [comment]
VLC build is 2.2.1 

The suggested timeout produces same crash, `console.log(chimera_player.state())` produces **playing** rather than **paused**. (I call `console.log ` after `chimera_player.pause()`).

**Comment by jaruba** [comment]
@Chayemor where did you download the VLC build? From the VideoLan site?

**Comment by Chayemor** [comment]
(Yes) Forgot to link it, my bad.

**Comment by jaruba** [comment]
ok, i'll try your code too, i'm curious

**Comment by Chayemor** [comment]
The following seems to work too, but had you not suggested the `setTimeout` I don't think I would have come up with it. 

The state is still **playing** though, even after calling `chimera_player.pause()` . At least it doesn't crash now. Though seems strange to have to wait a second for that not to happen.

```
chimera_player.onPlaying(function(){
        chimera_player.pause();
	console.log( chimera_player.itemDesc(player.currentItem()).mrl + "   " + chimera_player.length() );
	console.log(chimera_player.state());
	
	setTimeout( function() {
		if(!chimera_player.next()){
			chimera_player.stop();
			chimera_player.clearPlaylist();
		}
	}, 1000);
	
});
```

**Comment by RSATom** [comment]
most libvlc commands are async, so it's normal not change state right after function call.

**Comment by jaruba** [comment]
yes, @RSATom is entirely correct, it gets changed to "paused" but not instantly, i tested it now

**Comment by jaruba** [comment]
the last code you posted works great for me too, it's quite creative also, such a unique way to find the length of media, lol

**Comment by jaruba** [comment]
you might want to look into using `ffprobe` for this though, in which case you won't need to use `wcjs` at all to get the lengths

**Comment by RSATom** [comment]
checked, it deadlocks on `stop()` deep inside libvlc... don't know why yet

**Comment by RSATom** [comment]
don't have a time to debug libvlc right now, it will be too long story... just will add `libvlc_media_get_duration` support to `VlcMedia`

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js/releases/tag/v0.2.3

**Comment by RSATom** [comment]
But I didn't test it.

**Comment by Chayemor** [comment]
Thanks for the release, but I don't quite understand how to integrate it with the existing node-module installed via "**npm install wcjs-player**".

**Comment by jaruba** [comment]
@Chayemor just do `npm install wcjs-player` again.. it builds the latest version of WebChimera.js

**Comment by Chayemor** [comment]
I've installed it again, I'm trying to access the "**duration**" read-only property that was added via:

`player.itemDesc(0).duration`

but it always returns **-1**. From reading around, seems it has to be parsed before accessing the duration. Effectively, the **parsed** read-only property returns **false**. I tried calling `player.itemDesc(0).parse()` but it states that the function is **_undefined_**. 

Am I accessing the VlcMedia object wrong?

**Comment by RSATom** [comment]
@Chayemor,
> I tried calling  player.itemDesc(0).parse()  but it states that the function is undefined. 

maybe it's a but, I should check

**Comment by RSATom** [comment]
@Chayemor, did you try call `player.vlc.playlist.items[0].parse() `? Is it `undefined` too?

**Comment by Chayemor** [comment]
It works fine, I wrote it on the comment.

**Comment by RSATom** [comment]
@Chayemor, then it just missed in `wcjs-player`. You can access it via `player.vlc.playlist.items[0].parse() ` and it's ok. And yes, it's synchronous.

**Comment by Chayemor** [comment]
Works great by the way.

**Comment by RSATom** [comment]
@Chayemor, good news! Please close this issue then.
