### ISSUE TITLE
Delay when change vocal

### ISSUE THREAD

**Issue by creativefull** [jaruba/wcjs-player#49]
Can I replace the vocals without having to pause the audio ?

I feel less comfortable if the video has a delay when changing vocal .

can you give me solution about this problem ? 

thnks :)

**Comment by RSATom** [comment]
What do you mean by "replace the vocals" ?

**Comment by jaruba** [comment]
@creativefull the audio does not "pause", it buffers the new audio track.. the buffering time can be shorter or longer, depending on the value you set for`buffer` in `.addPlayer`. `buffer` can be set to anything between `0` and `60000` (milliseconds)
