### ISSUE TITLE
Visual Studio Community 2015

### ISSUE THREAD

**Issue by kevkha** [jaruba/wcjs-player#5]
I'm glad to see this new project. Can I use VSC 2015 instead of VSC 2013 to install this module on Windows 7?

**Comment by jaruba** [comment]
I'm afraid not, it needs to be VSC 2013 for the moment.

But Visual Studio 2013 Community is free and can be downloaded from this link:
https://www.visualstudio.com/en-us/products/visual-studio-community-vs.aspx

**Comment by RSATom** [comment]
@kevkha, I didn't try VSC2015 with `WebChimera.js` yet, but I don't think you will have any problems with it.

The only reason why I would not recommend Visual Studio 2015 to use - it's still in RC state...

**Comment by kevkha** [comment]
I uninstalled VSC2015 and installed VSC2013 but not sure why I keep getting below errors. 
<pre>
info RUN cmake "C:\WCJS\node_modules\wcjs-pla
yer\node_modules\wcjs-renderer\node_modules\webchimera.js" --no-warn-unused-cli
-G"Visual Studio 14 2015 [arch] Win64" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_JS_I
NC="C:\Users\KevKha\.cmake-js\nw-x64\v0.12.2\src;C:\Users\KevKha\.cmake-js\nw-x64\
v0.12.2\deps\v8\include;C:\Users\KevKha\.cmake-js\nw-x64\v0.12.2\deps\uv\include"
 -DNODE_RUNTIME="nw" -DNODE_RUNTIMEVERSION="0.12.2" -DNODE_ARCH="x64" -DCMAKE_JS
_LIB="C:\Users\KevKha\.cmake-js\nw-x64\v0.12.2\x64\nw.lib"
Not searching for unused variables given on the command line.
CMake Error: Could not create named generator Visual Studio 14 2015 [arch] Win64
...
.....
ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (C:\WCJS\node
_modules\wcjs-player\node_modules\wcjs-renderer\node_modules\webchimera.js\node_
modules\cmake-js\lib\cMake.js:367:24)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
wcjs-player@0.2.9 node_modules\wcjs-player
├── jquery@2.1.4
└── wcjs-renderer@0.1.3 (webchimera.js@0.1.18)
</pre>
I checked PATH but not sure why the cmake sets this <pre>-G"Visual Studio 14 2015 [arch] Win64"</pre>

I also see this variable sets for VSC2013 properly.
<pre>
var name: VS120COMNTOOLS
value: C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\Tools\
</pre>

**Comment by RSATom** [comment]
It seems cmake still thinking you have installed VSC2015. Tbh, I don't know how exactly cmake detects build environments.

**Comment by kevkha** [comment]
I gonna try to uninstall cmake and wipe any cache files and try again. Thanks.

**Comment by RSATom** [comment]
I think it will not help :) Try remove all references to VSC2015 from registry at key: `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\VisualStudio` 
Or you could just stay with VSC2015 - it should work.

**Comment by kevkha** [comment]
Thanks RSATom. I found VSC2015 in the registry and deleted. Now it detects the right VS version but still no joy :( I tried with both regular and "Run as administrator" when open CMD. Any other suggestion?

<pre>
info RUN cmake "C:\WCJS\node_modules\wcjs-pla
yer\node_modules\wcjs-renderer\node_modules\webchimera.js" --no-warn-unused-cli
-G"Visual Studio 12 2013 [arch] Win64" -DCMAKE_BUILD_TYPE="Release" -DCMAKE_JS_I
NC="C:\Users\KevKha\.cmake-js\nw-x64\v0.12.2\src;C:\Users\KevKha\.cmake-js\nw-x64\
v0.12.2\deps\v8\include;C:\Users\Kevin\.cmake-js\nw-x64\v0.12.2\deps\uv\include"
 -DNODE_RUNTIME="nw" -DNODE_RUNTIMEVERSION="0.12.2" -DNODE_ARCH="x64" -DCMAKE_JS
_LIB="C:\Users\KevKha\.cmake-js\nw-x64\v0.12.2\x64\nw.lib"
Not searching for unused variables given on the command line.
CMake Error: Could not create named generator Visual Studio 12 2013 [arch] Win64

ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (C:\WCJS\node_modules\wcjs-player\node_modules\wcjs-renderer\node_modules\webchimera.js\node_
modules\cmake-js\lib\cMake.js:367:24)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
</pre>

**Comment by RSATom** [comment]
@kevkha, what command you use to build? And why it tries build x64 version? - did you define it?

**Comment by kevkha** [comment]
I did not define the architecture bit. I simply follow the instructions from the README file and just add <code>--save</code> option
<pre>npm install --save wcjs-player</pre>

**Comment by RSATom** [comment]
hm... by default it should build x86 version.

**Comment by kevkha** [comment]
Maybe it reads the info from the cmake-gui. I attempted to build x64 earlier using cmake-gui for Webchemera.js and it worked there. Let me try to delete cache file and try again.

**Comment by RSATom** [comment]
I think I know the reason, it seems you have x64 Node.js (or io.js) installed. And on Windows cmake-js build addon with same bits as Node.js/io.js. Could you try install `ia32` version?

**Comment by kevkha** [comment]
Yes! That was it. It went well this time. Thanks RASTom! Can you update the wiki?
<pre>Microsoft (R) Build Engine version 12.0.31101.0
[Microsoft .NET Framework, version 4.0.30319.0]
Copyright (C) Microsoft Corporation. All rights reserved.
......

Build succeeded.
    0 Warning(s)
    0 Error(s)</pre>

**Comment by RSATom** [comment]
tbh, I don't think it's right solution. We shouldn't force users setup specific Node.js/io.js version. But different workarounds exists:
* You could `set npm_config_wcjs_arch="ia32"` before build
or
* You could define arch in your application `package.json`. Please read this: https://github.com/unbornchikken/cmake-js#nwjs

All these methods has disadvantages, and I don't sure this time which will be better to use.

**Comment by kevkha** [comment]
Good point! I will give it a shot with x64 again with provided info. Thanks.

**Comment by RSATom** [comment]
Thanks, but I still should think about best way to specify desired runtime options...

**Comment by RSATom** [comment]
I fixed selection of arch on windows, now it will be `ia32` by default, even if x64 `io.js` using.

btw, I think this issue could be closed.

**Comment by jaruba** [comment]
done, thanks :)
