### ISSUE TITLE
problem with nwjs 0.13.4 

### ISSUE THREAD

**Issue by kazemihabib** [jaruba/wcjs-player#50]
It works great with version 0.12 but with version 0.13.4 gives "Cannot read property 'addRule' of undefined" . at "wcjs-player/index.js:41"
I installed the wcjs-player with npm and extract the vlc in the root.

**Comment by jaruba** [comment]
I think `WebChimera.js` doesn't work yet with NW.js 0.13.x at all, check this ticket for more info:
https://github.com/RSATom/WebChimera.js/issues/72

**Comment by RSATom** [comment]
https://github.com/RSATom/WebChimera.js/releases/tag/v0.2.4
