### ISSUE TITLE
.aspectRatio("16:9") won't work first time.

### ISSUE THREAD

**Issue by Chayemor** [jaruba/wcjs-player#53]
Electron  0.37.2
Node.js 4.2.4
VLC 2.2.1
Windows 8.1

```
var video = new wjs("#vid").addPlayer({autoplay: false, titleBar: "none"});
video.aspectRatio("16:9");
video.play();
```

On first call there's no change, the window size (where video is located) is **320pxx180px** yet it displays this tiny black lines on left and right (shown in first picture). 

In order to get it to be "16:9" I have to first call `video.aspectRatio(sometingDifferent); `then do `video.aspectRatio("16:9");`

Am I using the function wrong?

![1](https://cloud.githubusercontent.com/assets/3482816/15015928/d8fd3d2a-120e-11e6-84ec-c53f4a77e683.png)
![2](https://cloud.githubusercontent.com/assets/3482816/15015927/d8fc8f74-120e-11e6-9cc9-be6107ccaaa6.png)

**Comment by jaruba** [comment]
Starting to play a media item resets aspect ratio to default, so you setting it to "16:9" before playback will do nothing.

**Comment by Chayemor** [comment]
I tried : 
```
video.play();
video.aspectRatio(aspectRatio);
```
but the first it does nothing either.

**Comment by jaruba** [comment]
the only thing you can do is do it in the `playing` event, but it might still need a small timeout to work.

**Comment by jaruba** [comment]
But.. the thing with `playing` is that it always triggers even when switching from `paused` to `playing`, not only at the start.

I could make a `firstPlay` event, that is sent only when a new item starts playing, after the change to the aspect happens, if you want. In which case, the code would be as easy as:
```
player.onFirstPlay(function() {
    video.aspectRatio(aspectRatio);
});
```

How does that sound?

**Comment by Chayemor** [comment]
That would be great. My project needs it since there's a whole list of videos that need to be played and the aspect ratio needs to be set every time. 

Thanks.

**Comment by jaruba** [comment]
Cool, do you want to make a PR for it? It's super easy to do as the player already distinguishes the first play of every media file over other play events.

At [this line](https://github.com/jaruba/wcjs-player/blob/master/index.js#L1386) you should add:
```

vlcs[this.context].events.emit('FirstPlay');

```

And at the end of the file, after [this line](https://github.com/jaruba/wcjs-player/blob/master/index.js#L1843) you should add:

```
wjs.prototype.onFirstPlay=function(wjsFunction){vlcs[this.context].events.on('FirstPlay',wjsFunction);return this}
```

That's about it. :)

**Comment by Chayemor** [comment]
First time I do a pull request (yay!... ?) Am, hope I didn't screw it up.

**Comment by jaruba** [comment]
nope, it's fine, i'll fix the indent. did you test it first though to make sure it works for your needs?

**Comment by Chayemor** [comment]
Yup, no longer need that nasty `setTimeOut(..)`

**Comment by jaruba** [comment]
great :)
