### ISSUE TITLE
vlcMedia.duration returns 0 after vlcMedia.parse() but still plays it

### ISSUE THREAD

**Issue by Chayemor** [jaruba/wcjs-player#54]
I have encountered a problem with ".mpg" videos. Files are parsed and only after `vlcMedia.parsed` is true do I try to access `vlcMedia.duration`. It works great with all file formats except ".mpg" (MPEG codec). If I open the video with VLC Player, the duration shows fine, it's when I try to get it through code that it doesn't work. The duration always returns **0** even if I do **setTimeOuts ** after parsing. Here is the thing, when played, the duration shows up on the WCJS-PLAYER just fine.

![mpgerror](https://cloud.githubusercontent.com/assets/3482816/15109115/fbba7a66-15d9-11e6-8d6a-2b198d39c965.png)

**Comment by jaruba** [comment]
That's part of the `WebChimera.js` official JS API, so only @RSATom can help with it. :/
