### ISSUE TITLE
TypeError: Cannot set property 'setting' of undefined

### ISSUE THREAD

**Issue by zxvfbg** [jaruba/wcjs-player#58]
I am using nwjs-sdk-v0.15.0-win-ia32.zip with WebChimera.js_v0.2.5_nw_v0.15.0_VLC_v2.2.3_ia32_win.zip from RSATom prebuilt releases

i can see the player loading the UI, but right before play there is a error:

C:\node\node_modules\wcjs-player\index.js:631 Uncaught TypeError: Cannot set property 'setting' of undefined

which corresponds to:

this.vlc.playlist.items[this.itemCount()-1].setting = "{}"; 

in index.js of wcjs-player

May be some updates in the VLC libs ?

**Comment by jaruba** [comment]
It's a plausible theory, Ivo. And if your right, that can cause major problems with all future versions of VLC.

I've never seen it before, so I don't know what to tell you.. Try VLC 2.2.1..

**Comment by jaruba** [comment]
I've caught this error myself now, @RSATom , there is a really big issue with WebChimera.js v0.2.5 in combination with VLC 2.2.3.

I downloaded:
`WebChimera.js_v0.2.5_electron_v0.33.9_VLC_v2.2.3_ia32_win.zip`

No errors loading WebChimera.js

But these two commands do nothing:
```
wcjs.playlist.add('http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4')
```

```
wcjs.play('http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4')
```

`wcjs.playlist.items` is always `0` after using them, nothing ever gets added to the playlist and playback never starts.

**Comment by jaruba** [comment]
@RSATom False alarm, I just forgot to add: https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows

@zxvfbg See if that fixes your problem.

**Comment by zxvfbg** [comment]
Yep i have see that :) Now its working.

I also made a exe from the RSATom batch file which starts nw.exe in invisible mode.

https://drive.google.com/open?id=0B14V_lSn_yKLX3FUa3pzbFFYcnc

**Comment by RSATom** [comment]
@zxvfbg, please remove link to executable file from message.

**Comment by RSATom** [comment]
@jaruba, please remove this link: https://www.virustotal.com/en/file/b58af8e5b96866dc2d6f9d20cf18459af77eec0b306671a47e463131d364d185/analysis/1464866200/

**Comment by jaruba** [comment]
@RSATom done :)
