### ISSUE TITLE
Play a video without creating any playlist?

### ISSUE THREAD

**Issue by Zzzen** [jaruba/wcjs-player#59]
The following code should work.
```
player = new wjs("#player").addPlayer({ autoplay: true });
player.play("file:///E:/2.flv");
```
But it is not. I have to add it to playlist before playing it. Otherwise, the player does nothing,

**Comment by jaruba** [comment]
Try:
```
player.vlc.play("file:///E:/2.flv");
```

**Comment by Zzzen** [comment]
Thanks.

**Comment by jaruba** [comment]
:wink:

**Comment by jaruba** [comment]
Also, it should be noted that the `wcjs-player` JS API is built above the `WebChimera.js` JS API.

You could always use anything from the `WebChimera.js` JS API ([docs here](https://github.com/RSATom/WebChimera.js/wiki/JavaScript-API)) with `player.vlc`, but, where possible, it is recommended to use the `wcjs-player` JS API as in some cases it _might_ have extra stuff to make sure the UI is handled correctly for those particular method calls.
