### ISSUE TITLE
Not able to launch nw.js app after installing wcjs-player module

### ISSUE THREAD

**Issue by kevkha** [jaruba/wcjs-player#6]
Not able to launch nw.js app after installing wcjs-player module.

Uncaught .../node_modules/wcjs-player/index.js:73
TypeError: Cannot read property 'firstChild' of null

**Comment by jaruba** [comment]
could you post the code with which your initializing the player?

**Comment by kevkha** [comment]
Exactly from the readme for Usage Example 1. The js code in my app.js and the player tag in index.html

**Comment by jaruba** [comment]
What OS and NW.js or Electron version?

**Comment by jaruba** [comment]
Also, please add this line before the one that gives the error:

    console.log(this.context);

and write here the result from the console.

**Comment by kevkha** [comment]
Win7 x64 and NW.js v0.12.2

<pre>C:\Users\KevKha\Documents\nwProjects\wcjs>gulp run
[15:07:09] Using gulpfile ~\Documents\nwProjects\wcjs\gulpFile.js
[15:07:09] Starting 'run'...
Latest Version: v0.12.2
Using v0.12.2
Create cache folder in C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\node-webkit-builder\cache\0.12.2
Using cache for: win64
Launching App</pre>
I'm working on the log now... stay tune! Thanks.

**Comment by jaruba** [comment]
Did you try the demo app?

Single Player:
https://github.com/jaruba/node-vlcPlayer-demo

Multiscreen:
https://github.com/jaruba/node-vlc-multiscreen

**Comment by kevkha** [comment]
Log <pre>
#player C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\wcjs-player\index.js:73
Uncaught C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\wcjs-player\index.js:74
TypeError: Cannot read property 'firstChild' of null</pre>

No, I have not tried the demo. Will give it a shot next. Thanks.

**Comment by jaruba** [comment]
Error says you don't have a ``<div>`` with the ``player`` id set.

Maybe you wrote the id wrong or your adding the div dynamically to the page with JS? (ie: it's not yet created when ``.addPlayer()`` is called)

**Comment by kevkha** [comment]
I do have that div line (copied from example 1) in my index file. My app.js is a module ( last line of app.js has module.exports = app; ) and I think I need more work there.

**Comment by jaruba** [comment]
it shouldn't be a problem.. all modules are attached to the same ``window.document``, are you by any chance using ``require()`` in the ``<head>`` of your HTML page? (ie: before the html elements are processed)

**Comment by kevkha** [comment]
required() only in app.js here is my index.ejs and btw I use angular as well

```javascript
var express = require('express'),
  path = require('path'),
  cookieParser = require('cookie-parser'),
  bodyParser = require('body-parser');

var wjs = require("wcjs-player");
var player = new wjs("#player").addPlayer({ autoplay: true });

app.player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");

// from here on you can either call the player with 'player' or 'wjs("#player")'

var routes = require('./routes');

var app = express();
// MORE CODES HERE....
```
```html
<!DOCTYPE html>
<html ng-app="wcjs">
<head>
<title>qikbox</title>
  <link rel="stylesheet" href="css/app.css">
  <link rel="stylesheet" href="libs/bootstrap/dist/css/bootstrap.min.css">
  <script src="libs/angular/angular.min.js"></script>
  <script type="text/javascript" src="libs/jquery/dist/jquery.min.js"></script>
  <script type="text/javascript" src="libs/bootstrap/dist/js/bootstrap.min.js"></script>

  <script src="js/app.js"></script>
</head>

<body>

<div class="container">
   <div ng-include src="'partials/head.html'"></div>
   <h3>Hello node-webkit express angular App!!</h3>
   <div id="player"></div>
</div>
</body>

</html>
```

**Comment by jaruba** [comment]
Try this:

	<!DOCTYPE html>
	<html ng-app="wcjs">
	<head>
	<title>wcjs</title>
	  <link rel="stylesheet" href="css/app.css">
	  <link rel="stylesheet" href="libs/bootstrap/dist/css/bootstrap.min.css">
	  <script src="libs/angular/angular.min.js"></script>
	  <script type="text/javascript" src="libs/jquery/dist/jquery.min.js"></script>
	  <script type="text/javascript" src="libs/bootstrap/dist/js/bootstrap.min.js"></script>
	
	</head>
	
	<body>
	
	<div class="container">
	   <div ng-include src="'partials/head.html'"></div>
	   <h3>Hello node-webkit express angular App!!</h3>
	   <div id="player"></div>
	</div>
	<script src="js/app.js"></script>
	</body>
	
	</html>

**Comment by kevkha** [comment]
Thanks but didn't help. I tried it before :)
I created my project using https://github.com/arvindr21/slush-wean
If you have time can you try out please?
<pre>
npm install -g gulp bower slush slush-wean
mkdir wcjs && slush wean
cd wcjs
npm install --save wcjs-player
# update app/app.js and app/views/index.ejs with example 1 code
gulp run
</pre>

**Comment by jaruba** [comment]
How about:

	var express = require('express'),
	  path = require('path'),
	  cookieParser = require('cookie-parser'),
	  bodyParser = require('body-parser');
	
	var wjs = require("wcjs-player");
	var player;
	
	$( document ).ready(function() {
		console.log( "ready!" );
		player = new wjs("#player").addPlayer({ autoplay: true });
		player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
	});
	
	// from here on you can either call the player with 'player' or 'new wjs("#player")'
	
	var routes = require('./routes');
	
	var app = express();
	// MORE CODES HERE....

**Comment by kevkha** [comment]
It didn't like like. Getting 
<pre>Uncaught ReferenceError: $ is not defined ...app/app.js:9</pre>

**Comment by jaruba** [comment]
maybe change:

    $(document).ready(function() {

to:

    jQuery(document).ready(function() {

?

**Comment by kevkha** [comment]
Uncaught ReferenceError: jQuery is not defined. Everything we throw in this app.js is not defined :) Do you think we need to tie with with variable app? Like app.player?

**Comment by jaruba** [comment]
neah, we'll just use the browser native event instead of the jquery one:

	var express = require('express'),
	  path = require('path'),
	  cookieParser = require('cookie-parser'),
	  bodyParser = require('body-parser');
	
	var wjs = require("wcjs-player");
	var player;
	
	window.onload = function() {
		console.log( "ready!" );
		player = new wjs("#player").addPlayer({ autoplay: true });
		player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
	};
	
	// from here on you can either call the player with 'player' or 'new wjs("#player")'
	
	var routes = require('./routes');
	
	var app = express();
	// MORE CODES HERE....

**Comment by kevkha** [comment]
You're a genius! app now can open though I don't see a video playing and there is no error. I'm looking into it now... thanks.

**Comment by jaruba** [comment]
Glad I could help, tell me if you have any more issues. :)

**Comment by kevkha** [comment]
Can't figure out why video is not playing. Want me to file new issue?

**Comment by jaruba** [comment]
Does the toolbar show?

**Comment by kevkha** [comment]
Yes, all elements appear except the player.

**Comment by jaruba** [comment]
what does:

   player.itemCount() 

return?

also try:

   player.zoom(1);
   player.playItem(0);

**Comment by kevkha** [comment]
Not seeing any text in dev tool console, interestingly not even from this line <code>console.log( "ready!" );</code>. So I suspect the <code>window.onload</code> is not working yet.

**Comment by jaruba** [comment]
what is this line from your code? what is it used for?

    bodyParser = require('body-parser');

**Comment by kevkha** [comment]
It's required for express 4. Rest of code in app.js
```javascript
// view engine setup
app.set('views', path.join(__dirname, 'views'));
app.set('view engine', 'ejs');

app.use(bodyParser.json());
app.use(bodyParser.urlencoded());
app.use(cookieParser());
app.use(express.static(path.join(__dirname, 'public')));

app.get('/', routes.index);

app.set('port', process.env.PORT || 3000);

var server = app.listen(app.get('port'), function() {
	// log a message to console!
});

module.exports = app;
```

**Comment by jaruba** [comment]
try it with this html file:
https://github.com/jaruba/node-vlcPlayer-demo/blob/master/index.html

**Comment by kevkha** [comment]
Sure, giving it a try now...
There is a second app.js under app/public/js directory and its contents which has the control elements written in anguar.js as followed. Wonder if we need part of wcjs-player code here.
```javascript
'use strict';

angular.module('qikbox', [])
  .factory('GUI', function() {
    return require('nw.gui');
  })
  .factory('Window', ['GUI', function(gui) {
    return gui.Window.get();
  }])
  .controller('Toolbar', ['$scope', 'Window',
    function($scope, Window) {
      /*
      
      Custom Control for Window operations
      */
      $scope.minimize = function() {
        Window.minimize();
      };

      $scope.toggleFullscreen = function() {
        Window.toggleKioskMode();
      };

      $scope.close = function() {
        Window.close();
      };
    }
  ]);
```

**Comment by jaruba** [comment]
> Wonder if we need part of wcjs-player code here.

don't think so..

**Comment by kevkha** [comment]
I tried the demo example and getting new error <code>Uncaught Error: %1 is not a valid Win32 application.</code> Build problem?
<pre>
C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\wcjs-player\node_mo…s-
renderer\node_modules\webchimera.js\node_modules\bindings\bindings.js:83 
Uncaught Error: %1 is not a valid Win32 application.
C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\wcjs-player\node_modules\wcjs-renderer\node_modules\webchimera.js\build\Release\WebChimera.js.node
</pre>

**Comment by jaruba** [comment]
yup..

**Comment by kevkha** [comment]
I thought RSATom fixed it from issue #5 :)

**Comment by jaruba** [comment]
did you add the vlc binaries to the folder?

**Comment by jaruba** [comment]
are you using NW.js 32bit or 64bit?

**Comment by kevkha** [comment]
Isn't <code>npm install wcjs-player</code> supposed to add the vlc bin part? gulp pulls the 64-bit version of NW.js

**Comment by jaruba** [comment]
Nope, you still need to add whatever vlc version you want to the package, just drop all the files from a vlc package to the root folder of your app, explained here:

https://github.com/RSATom/WebChimera.js#build-prerequisites

also, by default, ``WebChimera.js`` compiles for 32bit applications, you will need to rebuild with arguments``webchimera.js``:

	git clone https://github.com/jaruba/node-vlcPlayer-demo.git
	cd node-vlcPlayer-demo
	
	set npm_config_wcjs_runtime="nw"
	set npm_config_wcjs_runtime_version="0.12.2"
	set npm_config_wcjs_arch="ia64"
	
	npm install

**Comment by jaruba** [comment]
> I do have that div line (copied from example 1) in my index file. My app.js is a module ( last line of app.js has module.exports = app; ) and I think I need more work there.

but your calling ``app.js`` with:

    <script src="js/app.js"></script>

I don't think ``module.exports`` works outside the ``require()`` call.

Please try it like this:

	<!DOCTYPE html>
	<html ng-app="wcjs">
	<head>
	<title>wcjs</title>
	  <link rel="stylesheet" href="css/app.css">
	  <link rel="stylesheet" href="libs/bootstrap/dist/css/bootstrap.min.css">
	  <script src="libs/angular/angular.min.js"></script>
	  <script type="text/javascript" src="libs/jquery/dist/jquery.min.js"></script>
	  <script type="text/javascript" src="libs/bootstrap/dist/js/bootstrap.min.js"></script>
	
	</head>
	
	<body>
	
	<div class="container">
	   <div ng-include src="'partials/head.html'"></div>
	   <h3>Hello node-webkit express angular App!!</h3>
	   <div id="player"></div>
	</div>
	<script>
	var app = require("js/app.js");
	</script>
	</body>
	
	</html>

**Comment by kevkha** [comment]
Yes, sorry the confusion was from my end. js/app.js is for front end and app/app.js is back end.

**Comment by jaruba** [comment]
Building VLC takes a very, very long time.. :)

Ofc we've thought of this, but we haven't yet found  any good solution to add vlc automatically.

@RSATom should be better equipped to answer such a question though.

**Comment by RSATom** [comment]
~~`set npm_config_wcjs_arch="ia64"`~~ `set npm_config_wcjs_arch="x64"` should be used for 64 bit

**Comment by RSATom** [comment]
About vlc binaries: on Windows it's better have them near the .exe or in the PATH, but it's not possible with npm install it there.

**Comment by kevkha** [comment]
Thanks both. Finally, I got the demo to run successfully with nw.js ia32. Will try to run again with my "slush wean" project.

Is it possible to place vlc binaries in a folder ie "vlc" to keep things organized like we have a "plugin" folder in the other project? Placing them in the root of project folder does not look clean imo.

**Comment by RSATom** [comment]
@kevkha, if you are on Windows - I'm afraid not: https://msdn.microsoft.com/en-us/library/windows/desktop/ms682586%28v=vs.85%29.aspx#search_order_for_desktop_applications

**Comment by kevkha** [comment]
On Windows vlc in PATH works so I will look at this alternative. Thanks.
Since I haven't figured out for gulp to run nw.js 32-bit on Win7 x64 I attempted to build wcjs-player win64 but getting errors here.

<pre>
mkdir wcjs && slush wean

set npm_config_wcjs_runtime="nw"
set npm_config_wcjs_runtime_version="0.12.2"
set npm_config_wcjs_arch="x64"

npm install --save wcjs-player
</pre>
During the install it fails with below at the end.
<pre>

    14 Warning(s)
    81 Error(s)

Time Elapsed 00:00:14.19
ERR! OMG Process terminated: 1
Unhandled rejection Error: Process terminated: 1
    at ChildProcess.<anonymous> (C:\Users\KevKha\Documents\nwProjects\wcjs\node_modules\wcjs-player\node_modules\wcjs-renderer\no
de_modules\webchimera.js\node_modules\cmake-js\lib\cMake.js:366:28)
    at ChildProcess.emit (events.js:110:17)
    at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
wcjs-player@0.4.0 node_modules\wcjs-player
├── jquery@2.1.4
└── wcjs-renderer@0.1.3 (webchimera.js@0.1.22)
</pre>

Has anyone successfully built wcjs-player with win64 arch on Win7 x64 with NW.js x64?

**Comment by jaruba** [comment]
https://github.com/RSATom/wcjs-ugly-demo/issues/3#issuecomment-119812805

**Comment by jaruba** [comment]
srry, closed it by mistake :)

**Comment by kevkha** [comment]
@jaruba Thanks for the info. It helps however how do I modify it when wcjs-player handles the install?
If I figured out to have gulp to build ia32 for NW.js I won't bother dealing win64.

**Comment by jaruba** [comment]
you could try just using:

    set npm_config_wcjs_arch="ia32"

before installing with gulp, it might work. :)

**Comment by jaruba** [comment]
oh, does gulp download NW.js 64bit by default too?

**Comment by jaruba** [comment]
http://stackoverflow.com/questions/30403358/how-to-tell-gulp-which-version-of-node-webkit-to-use

**Comment by kevkha** [comment]
I have no problem creating ia32 build using your demo but with <code>gulp</code> and <code>slush wean</code> project, it creates x64 by default (or based on arch of OS). I hacked the gulpFile.js to add arg <code>-p win32</code> but <code>gulp run</code> isn't work. Thanks for the link! Checking...

**Comment by jaruba** [comment]
@kevkha did you have any more problems? can this issue be closed?

**Comment by kevkha** [comment]
Yes, still have problem but it's not wcjs-player issue. Ok to close. Thanks.
I filed a new issue here https://github.com/mllrsohn/node-webkit-builder/issues/240.
