### ISSUE TITLE
Exports empty object

### ISSUE THREAD

**Issue by amilajack** [jaruba/wcjs-player#65]
The following code logs an empty object:
```js
var wjs = require('wcjs-player');

console.log(wjs); // {}
```

I am using webpack. This only happens when the module is not being included at before bundling. But when bundling the dependency at compile time, I get this error:

```
path.js:7Uncaught TypeError: Path must be a string. Received undefined
```

![screen shot 2016-07-07 at 9 42 56 pm](https://cloud.githubusercontent.com/assets/6374832/16677520/cf754306-448b-11e6-8806-e6376c679ac9.png)

**Comment by jaruba** [comment]
that's impossible because it doesn't even return an object, it returns a function

**Comment by jaruba** [comment]
https://github.com/jaruba/wcjs-player/blob/master/index.js#L71
https://github.com/jaruba/wcjs-player/blob/master/index.js#L1861

**Comment by amilajack** [comment]
Updated my question and added more information. Hope it helps/

**Comment by amilajack** [comment]
Hmm.. I think it could be an issue with the compatibility between ES6 modules or modules loaders. I'll fork this repo and mess around with it.

**Comment by jaruba** [comment]
I don't think this is related to my player at all, as I have no `path.js` nor do I use `path` for anything in the player. It may be a side-effect of some other issue.

**Comment by amilajack** [comment]
Yea, I think the module loader is using some internal path file to resolve a path.

**Comment by jaruba** [comment]
Oh, I do use path
```
    path = require('path'),
    relbase = "./"+path.relative(path.dirname(require.main.filename), __dirname),
```

Seems I use it to find the path to the css file (that the player injects) and for the path of an image in the playlist.

**Comment by jaruba** [comment]
maybe `require.main.filename` becomes `undefined` for some reason after webpack does it's mojo?

**Comment by jaruba** [comment]
I'd do a `console.log(__dirname)` in `index.js` from `wcjs-player` on the very first line to see what it returns, then tinker with `relbase = ` until it satisfies the circumstances of a webpack build

**Comment by amilajack** [comment]
The output of `console.log(__dirname)` is `/` and the output of `console.log(require.main.filename);` is `undefined`.

**Comment by jaruba** [comment]
damn.. does webpack blob everything (including `node_modules`) into 1 file?

**Comment by amilajack** [comment]
It includes everything that you tell it to. It also uses tree-shaking to 'shake off' dependencies that you aren't using.

**Comment by jaruba** [comment]
try `process.cwd()` instead of `require.main.filename` then

**Comment by amilajack** [comment]
What is the `relbase` supposed to mean?

**Comment by jaruba** [comment]
relative path to the `wcjs-player` folder, this is needed as it's injecting css and html, so the css and html need the relative path (from your main entry point, most probably your app's `index.html`) to `wcjs-player`'s folder in order to fetch the CSS file, fonts and 1 image (i should really move this image to base64 and put it in the CSS file though)

**Comment by amilajack** [comment]
`process.cwd()` gives me: `/Users/amila/Documents/Projects/popcorn-desktop-experimental`. How would I disable the injection?

**Comment by jaruba** [comment]
you can't... the player is the injection (how else do you expect to add it's html to the page?), just remove these lines:

```
    path = require('path'),
    relbase = "./"+path.relative(path.dirname(require.main.filename), __dirname),
```

and add:

```
    relbase = process.cwd(),
```

in it's place

**Comment by jaruba** [comment]
or maybe try using the `file:` protocol for it, try:

```
    relbase = 'file://' + process.cwd(),
```

or

```
    relbase = 'file:///' + process.cwd(),
```

**Comment by amilajack** [comment]
I somewhat fixed the issue by excluding the file from webpack:

```js
// webpack.config.js
{
  //...
  externals: [
    'wcjs-player'
  ]
}
```

**Comment by amilajack** [comment]
It plays now! But the problem now is that it doesnt render correctly. The html is rendered inside of the canvas element, which I think should be invalid:
![screen shot 2016-07-07 at 11 42 56 pm](https://cloud.githubusercontent.com/assets/6374832/16679469/ae69d7e2-449c-11e6-8c92-b1dcbe1aad51.png)

**Comment by jaruba** [comment]
did you follow the example in the readme? it injects the player where you tell it to, so you obviously initiated the player on a canvas instead of a div..

**Comment by amilajack** [comment]
Created the canvas element because of `wc-render` and forgot to change it. Sorry about that.

**Comment by RSATom** [comment]
@amilajack, FYI: https://github.com/jaruba/wcjs-player/issues/72#issuecomment-240710219
