### ISSUE TITLE
WCJS player in Elecrton app doesn't work after it has been compiled

### ISSUE THREAD

**Issue by skaynetmen** [jaruba/wcjs-player#68]
If I start Electron without compilation - it works perfect. But if I compile it with electron-packager - player doesn't work and shows the black screen.

![6e5a08fe75](https://cloud.githubusercontent.com/assets/5357263/17063654/0993526a-5041-11e6-8878-d26c57495a06.jpg)

OS X 10.10.5
electron 1.2.6
wcjs-player 6.0.1
wcjs-prebuilt 3.0.0

a similar problem https://github.com/jaruba/wcjs-player/issues/21

**Comment by RSATom** [comment]
Binary modules will not work if packaged to any archive.

**Comment by skaynetmen** [comment]
> Binary modules will not work if packaged to any archive.

Yes, I understand, but this is an package for os x

**Comment by RSATom** [comment]
>  this is an package for os x

i.e. `bundle` in Apple terms.

It's just folder, so look inside, and check all binary modules are there.

**Comment by skaynetmen** [comment]
> i.e. bundle in Apple terms.
> It's  just folder, so look inside, and check all binary modules are there.

I replaced webchimera's files in electron.app and everything starts to work. Thank you!

**Comment by heuuLZP** [comment]
I have the same problem in OSX . I can't understand your answer.  

I am not found `bundle` .  What should I do ?  @skaynetmen   @RSATom 

This is contents of electron.app .

![image](https://cloud.githubusercontent.com/assets/18410118/23936909/9e414270-098f-11e7-8acc-639728c4db14.png)

**Comment by skaynetmen** [comment]
@heuuLZP 

![screenshot](http://joxi.net/52aEb07fj0Bn20.jpg)

Contents/Resources/app/node_modules/wcjs-prebuilt/

**Comment by heuuLZP** [comment]
I know this folder 'Contents/Resources/app/node_modules/wcjs-prebuilt/' , and then ? 

![image](https://cloud.githubusercontent.com/assets/18410118/23937327/fadd95b8-0991-11e7-894c-36c74d5cf9fb.png)

**Comment by RSATom** [comment]
It's hard to explain in details, but usually problem is in symlinks inside lib folder. So just extract files from archive for Mac OS X from [releases page](https://github.com/RSATom/WebChimera.js/releases)

**Comment by skaynetmen** [comment]
@heuuLZP 
Download WebChimera.js_v0.2.7_electron_v1.4.13_VLC_v2.2.4_x64_osx.tar.gz from [https://github.com/RSATom/WebChimera.js/releases](https://github.com/RSATom/WebChimera.js/releases) and replace files in Contents/Resources/app/node_modules/wcjs-prebuilt/bin/

**Comment by heuuLZP** [comment]
Before asking questions ，I download `WebChimera.js_v0.2.7_electron_v1.4.13_VLC_v2.2.4_x64_osx.tar`  。

Just now I replaced the contents of the folder `bin` , it's work ! 

thank you very much.

**Comment by heuuLZP** [comment]
@skaynetmen 
Hi , I have a question , can you help me ?  

Now I need to package the app to app.asar , you know the asar is can't open , so I can't replace these vlc's files.

Very large package using electron-package , so I using electron-builder ,and pack to dmg , but it's no app filder .

**Comment by skaynetmen** [comment]
Hi @heuuLZP 

[https://github.com/electron/asar](https://github.com/electron/asar)
`npm install -g asar`

`asar extract /path/to/app.asar ~/tmp`

replace bin files in ~/tmp

`asar pack ~/tmp ~/app.asar`

`cp ~/app.asar /path/to/app.asar`

**Comment by heuuLZP** [comment]
I understand your solution , but there have some questions about your answer.  

- first               
1.   I using electron-packageer to pack app;
   2.  Replaced the bin files   
   3.   asar app to app.asar   
   4.   remove app folder   (if remove app folder will have error, but I must remove that , it's  expose resource code)

- second   
1.   I using electron-builder to pack app.
   2.  it's will pack to app.dmg    
    
   You know the app.dmg  can use after install  , I want to make the app.dmg is normal work.

**Comment by skaynetmen** [comment]
Have you tried to replace the files in the project folder before packaging?

If it still did not work, then there are 2 ways:
Do dmg manually, or try using the afterPack/beforeBuild callback function in [https://github.com/electron-userland/electron-builder/wiki/Options#Config](https://github.com/electron-userland/electron-builder/wiki/Options#Config)

Or Options.Config

asar: false,
extraResources: [ //list webchimera bin files
[FilePattern](https://github.com/electron-userland/electron-builder/wiki/Developer-API#FilePattern)
]

**Comment by heuuLZP** [comment]
YES. I had try that . It's has replaced files inner asar .      It's not work .  

I want to only the asar , don't have  app folder, but can't work .
 

I have an important question .  The asar is not secrecy ，because people can use `asar extract /path/to/app.asar ~/tmp`  to  get resource .

**Comment by skaynetmen** [comment]
Yes it is. Anyone can access the app files if they want to)
