### ISSUE TITLE
Video doesn't play when app is launched

### ISSUE THREAD

**Issue by saru95** [jaruba/wcjs-player#7]
Video doesnt seem to play when launching NW.js app .

HTML 
```
<body style="-webkit-app-region: drag">

				<div id="magnetBox">
					<div class='cell'><input type='search' placeholder='Enter Magnet Link'></div>
  					<div class='cell'><div class='button'>Stream</div></div>
				</div>

				<div id="player" class="playerstyle"></div>

		<script type="text/javascript" src="vendors/js/jquery.min.js"></script>
		<script type="text/javascript" src="static/js/main.js"></script>
		<script type="text/javascript" src="static/js/torrent-server.js"></script>
		</body>
```

torrent-server.js 

```
var peerflix = require('peerflix'),
    engine = peerflix('magnet:?xt=urn:btih:120ad76789b11bce2d6005d1c22ccf1507c3021a&dn=Pink+-+Just+Give+Me+A+Reason+%28Ft.+Nate+Ruess%29+M4A%2BMP4+%281080p%29+x2&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80&tr=udp%3A%2F%2Fopen.demonii.com%3A1337&tr=udp%3A%2F%2Ftracker.coppersurfer.tk%3A6969&tr=udp%3A%2F%2Fexodus.desync.com%3A6969'),
    wjs = require("wcjs-player"),
    player = new wjs("#player").addPlayer({ autoplay: true });

//engine.server.on('listening', function() {
  //  var myLink = 'http://localhost:' + engine.server.address().port + '/';
    player.addPlaylist('http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4');
//});
```

I wanted to stream a torrent to it. But how can I if a normal video doesnt play . Need help on this ?

**Comment by jaruba** [comment]
does the toolbar show? do you have any errors in the dev console?

**Comment by saru95** [comment]
Yes the toolbar of the player gets displayed .

Error in console :
![screen shot 2015-07-10 at 10 08 05 pm](https://cloud.githubusercontent.com/assets/6523503/8623634/318f1c9c-2750-11e5-9a51-56cb1ee367dd.JPG)

**Comment by saru95** [comment]
Ignore the first error !

**Comment by jaruba** [comment]
:)

What OS are you using? (Mac?) and what version of NW.js? Is NW.js 32bit or 64bit?

**Comment by saru95** [comment]
Mac OSX Yosemite 10.10.3 . 
 nw.js - v0.12.2

**Comment by jaruba** [comment]
cool, is nw.js 64bit or 32bit?

**Comment by saru95** [comment]
64 bit

**Comment by jaruba** [comment]
did you add the VLC binaries to your app? Check [WebChimera.js Mac OS X Prerequisites](https://github.com/RSATom/WebChimera.js#mac-os-x) for a link to VLC binaries.

**Comment by saru95** [comment]
Yes, I have VLC player installed !

**Comment by jaruba** [comment]
not installed, you need to add the binaries to your app's archive package.

@RSATom @Ivshti care to join in on the discussion? :)

**Comment by saru95** [comment]
Can you explain how to do that ? Do you mean I need to install it inside my app folder also ?

**Comment by RSATom** [comment]
@jaruba, I'm here :)

@saru95, you have to add libvlc to your package. And you will save many time if will use this: https://github.com/RSATom/WebChimera.js/releases/download/v.0.1.3/libvlc_2.2.1_mac.zip

**Comment by saru95** [comment]
Thanks ! let me check it out ?

**Comment by RSATom** [comment]
@saru95, you need download archive mentioned above and extract it near the `webchimera.js.node`

**Comment by jaruba** [comment]
@RSATom please check private messages on gitter if you can. :)

**Comment by RSATom** [comment]
it seems I have to add it to readme...

**Comment by RSATom** [comment]
@jaruba, I'm there :)

**Comment by saru95** [comment]
Oh Yes Thanks a lot. the normal video works! let me try it out with a torrent stream now . Thank You !

**Comment by jaruba** [comment]
Did it work? Can we close the issue?

**Comment by saru95** [comment]
Ohh Yes thank you .

**Comment by siuying** [comment]
@RSATom can you advise anything special about the libvlc_2.2.1_mac.zip? I wonder why I cant just copy that from VLC.app folder. (I'm trying to automating the build of my app)

**Comment by RSATom** [comment]
@siuying, the reason is bug inside libvlc, witch don't allow it work correctly outside VLC.app. If you will use VLC 2.1.5 you could use it as is, without any additional magic.

**Comment by siuying** [comment]
@RSATom Thanks for the tips!

**Comment by heuuLZP** [comment]
@RSATom    

Hi, I have the same err .
The reason is I removed the app resource folder, and only have the asar.

The package is very larger, I `asar pack app  to app.asar`  , but only have asar  , it's not normal work .

can you help me ?

**Comment by RSATom** [comment]
@heuuLZP, I didn't work with asar. Sorry.
