### ISSUE TITLE
Cannot set property 'setting' of undefined

### ISSUE THREAD

**Issue by kbailles** [jaruba/wcjs-player#70]
After a few hours of finally getting the right versions aligned and arch whenever I run the player I get the error listed in the title. Anyone know why?

``` html
<!DOCTYPE HTML>
<html>

<head>
    <style>
        body,
        html {
            width: 100%;
            height: 100%;
            padding: 0px;
            margin: 0px
        }

        #player {
            width: 100%;
            height: 100%
        }
    </style>
</head>

<body>
    <div id="player"></div>
    <script>
        var wjs = require("wcjs-player");

        var player = new wjs("#player").addPlayer({
            autoplay: true,
            wcjs: require('wcjs-prebuilt')
        });

        //if I comment out this line I get no errors
        player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
    </script>
</body>

</html>
```

I'm running Electron version 1.3.1, wcjs-prebuilt 2.1.0, and the latest for wcjs-player. I've also tried to follow https://github.com/jaruba/wcjs-player/issues/58 and https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows... I had no luck. 

I put 

``` js
if (process.platform == 'win32') {
    process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, 'node_modules/wcjs-prebuilt/bin/plugins');
}
```

at the top of my main.js file but it didn't seem like it did anything.

Any help would be appreciated.

**Comment by jaruba** [comment]
I think the error still points to an issue with loading `WebChimera.js`. Try installing [DebugView](https://technet.microsoft.com/en-us/sysinternals/debugview.aspx) to see if there is any error from VLC.

**Comment by kbailles** [comment]
You were right. This is the error...
![vlc_error](https://cloud.githubusercontent.com/assets/8462812/17667236/aa98ffc6-62c9-11e6-891f-859f7390a338.PNG)

(Says "core lbvlc error: No plugins found! Check your VLC installation.)

But I have VLC installed... Is VLC_PLUGIN_PATH supposed to point to the prebuilt plugins folder or to the folder where VLC is installed?

**Comment by jaruba** [comment]
Prebuilt plugins folder

PS: I'm always right

**Comment by kbailles** [comment]
Any recommendations on the fix?

**Comment by jaruba** [comment]
```
if (process.platform == 'win32') {
    process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, 'node_modules/wcjs-prebuilt/bin/plugins');
}
```

^ set the correct path to the `plugins` folder here

**Comment by kbailles** [comment]
I did put

``` js
if (process.platform == 'win32') {
    process.env['VLC_PLUGIN_PATH'] = require('path').join(__dirname, 'node_modules/wcjs-prebuilt/bin/plugins');
}
```

At the top of my main.js for Electron but I'm still getting that error. I should have the correct version of VLC installed as well... 

![prebuilt_capture](https://cloud.githubusercontent.com/assets/8462812/17668679/12a3c3ca-62d0-11e6-8660-40b09e10a3e3.PNG)

That's my prebuilt folder and here's a capture of my main.js

![code_screengrab](https://cloud.githubusercontent.com/assets/8462812/17668933/3f283cfe-62d1-11e6-83cf-40c08aa5dae6.PNG)

I'm starting the application with this command:
`electron .`

index.html is same as my first post. It acquired `WebChimera.js_v0.2.6_electron_v1.3.1_VLC_v2.2.4_x64_win.zip` Still not finding VLC plugin...

**Comment by jaruba** [comment]
not `libvlc.dll`, the `/plugins/` folder, console log the path, see if it's correct

**Comment by kbailles** [comment]
Ok so my problem was not the /libvlc.dll (that was me testing different paths just to see), but doing `require('path').join(__dirname, 'node_modules/wcjs-prebuilt/bin/plugins')` was giving me an invalid path to the plugin folder... doing `require('path').join(__dirname, '../node_modules/wcjs-prebuilt/bin/plugins')` did give me the correct path and fixed my issue. Really appreciate your timely responses. All working now.
