### ISSUE TITLE
What is wrong !?!?!

### ISSUE THREAD

**Issue by lukas13on** [jaruba/wcjs-player#73]
I tried to put VLC Player files in (.\node_modules\wcjs-prebuilt\bin), (.\root), and whenever i start the application and nothing happens, it's just black and returns no errors, I'm already two days trying to setup, but it has become easy to hard too fast, and i no longer know what to do.

my system:
- Time of this report: 9/6/2016, 17:22:46
- Machine name: PIRATECOM-PC
- Operating System: Windows 7 Ultimate 64-bit (6.1, Build 7601) Service Pack 1 (7601.win7sp1_ldr.160408-2045)
- Language: Portuguese (Regional Setting: Portuguese)
- System Manufacturer: To be filled by O.E.M.
- System Model: To be filled by O.E.M.
- BIOS: BIOS Date: 06/20/12 13:41:17 Ver: 04.06.05
- Processor: AMD FX(tm)-8320 Eight-Core Processor            (8 CPUs), ~3.5GHz
- Memory: 8192MB RAM
- Available OS Memory: 8122MB RAM
- Page File: 4735MB used, 11507MB available
- Windows Dir: C:\Windows
- DirectX Version: DirectX 11
- DX Setup Parameters: Not found
- User DPI Setting: Using System DPI
- System DPI Setting: 96 DPI (100 percent)
- DWM DPI Scaling: Disabled
- DxDiag Version: 6.01.7601.17514 32bit Unicode

im using:
wcjs-player -> "version": "6.0.1"
wcjs-prebuilt -> "version": "3.0.0"
wcjs-renderer -> "version": "1.0.2"
electron-prebuilt ->"version": "1.3.2"

I installed with
$ npm install wcjs-player
$ npm install wcjs-prebuilt

``` json
  "wcjs-prebuilt": {
  "runtime": "electron",
  "platform":"win",
  "targetDir":"./bin",
  "arch":"x64"
}
```

here's my **.js**

``` javascript
var wjs = require("wcjs-player");
var player = new wjs("#player").addPlayer({
wcjs: require('wcjs-prebuilt')
});

player.vlc.play("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
player.play();
```

here's my **.html**

``` html
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <link rel="stylesheet" type="text/css" href="css/navigation.css"/>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </head> 
    <body>
        <div id="player"></div>
        <script>require('./renderer.js');</script>
    </body>
</html>
```

And when i trie to set a playlist returns a error:

``` javascript
player.addPlaylist("http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4");
```

_**C:\Users\PirateCom\pirateHangar\node_modules\wcjs-player\index.js:633 Uncaught TypeError: Cannot set property 'setting' of undefined**_

[Screenshot link](https://goo.gl/photos/n2vTYBY8Az8vCzdh8)

**Comment by jaruba** [comment]
`...\PirateCom\pirateHangar\...`

![giphy](https://cloud.githubusercontent.com/assets/1777923/18290775/7c83f700-748d-11e6-942c-313692bb9159.gif)

**Comment by jaruba** [comment]
anyway, i don't think that `WebChimera.js` is loaded correctly, please see this issue's comment: https://github.com/jaruba/wcjs-player/issues/72#issuecomment-240388653

**Comment by lukas13on** [comment]
I will check, update soon

**Comment by jaruba** [comment]
If it still doesn't work, also try using older Electron versions.

**Comment by jaruba** [comment]
Please remember to close the issue if it is solved. :)

**Comment by jaruba** [comment]
presuming it was solved due to inactivity
