### ISSUE TITLE
`addPlaylist()` results in `cannot set property "setting" of undefined`

### ISSUE THREAD

**Issue by erikyuzwa** [jaruba/wcjs-player#74]
Hi,
Just trying to use WebChimera in an Electron app and running into this issue.

```
var wjs = require('wcjs-player'); // valid object
var wcjsPrebuilt = require('wcjs-prebuilt); // valid object
var player = new wjs('#player1').addPlayer({
  autoplay: true,
 wcjs: wcjsPrebuilt
});

console.info(player); // object looks ok in the console
player.addPlaylist('http://archive.org/download/CartoonClassics/Krazy_Kat_-_Keeping_Up_With_Krazy.mp4'); // results in the error
```

https://github.com/jaruba/wcjs-player/blob/master/index.js#L633

All I can think of is to maybe use `item` instead of `this.itemCount()-1` since we're working with the current item vs. the last item in the `playlist` Array? I'm not sure what L632 and L633 are for (sorry!)

`player.version` = `v6.0.1`

Any ideas? thanks a lot. :bow:

**Comment by jaruba** [comment]
If it's windows, see this issue comment: https://github.com/jaruba/wcjs-player/issues/72#issuecomment-240388653

What Electron version? (you should also try older electron versions)

**Comment by erikyuzwa** [comment]
thanks - on a quick skim it does look relevant. I'm using `v1.3.5` of Electron. In case that's the issue, what release do you recommend for WebChimera?

**Comment by erikyuzwa** [comment]
sweet, that worked - still with `v1.3.5` of Electron

```
// in the main.js of your Electron app
let chimeraPath;
if (process.platform === 'win32') {
  chimeraPath = require('path').join(__dirname, 'node_modules/wcjs-prebuilt/bin');
  process.env['VLC_PLUGIN_PATH'] = chimeraPath;
}
```

**Comment by jaruba** [comment]
awesome ;)
