### ISSUE TITLE
video format is rmvb , the playlist item's title is 'Unkonwn' ?    

### ISSUE THREAD

**Issue by heuuLZP** [jaruba/wcjs-player#79]
Hi jaruba:

Recently I was using your wcjs-player. I met some problems, and  found  solutions.   

But today,  I meet a strange question. 

My video format is `.rmvb` , it can normaly play, but have two questions.

---             

### question one 

It's very strange, the title are changed !!!   Why change to `unknown` ???

the code site `wcjs-player/index.js`   line:632    

```
if (playlist[item].title) this.vlc.playlist.items[this.itemCount()-1].title = "[custom]"+playlist[item].title;
```

![image](https://cloud.githubusercontent.com/assets/18410118/23704575/997678fe-0440-11e7-9bff-a9e6a6c8e7e8.png)

![image](https://cloud.githubusercontent.com/assets/18410118/23704601/b400adf2-0440-11e7-9b85-a488d0537222.png)

### question two
![image](https://cloud.githubusercontent.com/assets/18410118/23704426/d9ae1676-043f-11e7-813b-21c472dda7b1.png)

I google and found it's maybe because  FFempeg Library file，but I can't solute. 

---  
please help me. thank you.

**Comment by jaruba** [comment]
The first question is interesting, it may be that vlc is changing the name somehow, please also try to play the same file but in a folder that lacks the chinese characters.

I don't know anything about the second question though, maybe @RSATom may know something.

**Comment by heuuLZP** [comment]
I did what you said. There are no works.   

I changed the folder name 
![image](https://cloud.githubusercontent.com/assets/18410118/23705627/b8f9d338-0445-11e7-85bb-13c006b44265.png)

it's also show `unknown`   

other format are normal  , example `avi` , `wmv` , `mp4' .

**Comment by RSATom** [comment]
I would recommend you open the same file in VLC and look if you will get something similar there...

**Comment by heuuLZP** [comment]
I just open the same file on `node-vlcPlayer-demo` ， it's normaly。  

I use electron to write the work , I will find the reason,  thanks to your very much  .

oh no no no, only original it is normaly, when I play the `124.rmvb` ,the title while change to `unknown`

How o'clock are  American  now,  it's maybe morning 7:00。  you wake up early

**Comment by heuuLZP** [comment]
I download the vlc player, and open the file `rmvb`, it 's also `unknow`.   
I download other video of `rmvb`  ,it's the same question.

**Comment by RSATom** [comment]
then it's some internal libvlc issue

**Comment by heuuLZP** [comment]
Any way, thank you for your replay.
