### ISSUE TITLE
Enhancement Request for Playlist Menu

### ISSUE THREAD

**Issue by kevkha** [jaruba/wcjs-player#8]
I see there is a CSS class for <code>wcp-playlist-item</code> I would like to override the following for Playlist Menu.

1. ability to change background
2. ability to change position
3. ability to resize
4. ability to navigate up/down playlist items by keyboard

Could you tell me which is doable now? Thanks.

**Comment by jaruba** [comment]
The CSS file is at ``/public/general.css``, so you can either change that file or you could just use any css style anywhere on your page and use ``!important`` ([read more about !important](http://stackoverflow.com/questions/9245353/what-does-important-in-css-mean)) at the end of every css line to make sure it overwrites ``general.css``.

By changing the css you can do nr. 1, 2 and 3. for nr 4 look into jquery, more specifically [.keypress()](https://api.jquery.com/keypress/) and [.animate()](http://api.jquery.com/animate/). Check [this stackoverflow answer](http://stackoverflow.com/questions/16586594/scroll-up-and-down-a-div-on-button-click-using-jquery#answer-16586662) for details and an example of how to scroll a DOM element.

**Comment by jaruba** [comment]
Btw, the CSS class for the menu is: ``wcp-playlist`` , ``wcp-playlist-item`` is (obviously) the class for every item in the playlist.

**Comment by kevkha** [comment]
Thanks @jaruba. Where is class wcp-playlist? I don't it in /public/general.css. Can you point me the line nr?

**Comment by jaruba** [comment]
It isn't mentioned in the CSS file because it does not have any special CSS to add above what ``wcp-menu`` has. You can just add it yourself. :)

**Comment by jaruba** [comment]
> Update: Got it. I have to create it something like this :)

> .wcp-playlist {
>     background: rgba(0,0,0,0.9);
> }

Semi-transparent black is always a favorite. :)
