### ISSUE TITLE
my demo cannot play rtsp

### ISSUE THREAD

**Issue by ilvlemon** [jaruba/wcjs-player#81]
I want to use electron with my windows desktop application, but I need a RTSP player with it . Then I find wcjs-player for it, but I have a problem.

My electron version is **1.4.3** .
My wcjs-prebuilt version is **3.0.0** .
My wcjs-player version is **6.0.1** .
This are all the newest version but electron , because the last version of WebChimera.js is :  **WebChimera.js_v0.2.7_electron_v1.4.3_VLC_v2.2.4_x64_win.zip** .

But, my player demo not work. 

My index.html is:
`<!DOCTYPE html>
<html>
  <head>
    <title>Hello World!</title>
	<style></style>
  </head>
  <body>
	<div id = "player"></div>
	<script>
	  var wjs = require("wcjs-player");
	  var player = new wjs("#player").addPlayer({autoplay:true,wcjs: require('wcjs-prebuilt')});
          player.addPlaylist({url:"rtsp://184.72.239.149/vod/mp4://BigBuckBunny_175k.mov",title:"the title"});
	</script>
  </body>
</html>`

My package.json is: 
{
  "name": "your-app",
  "version": "0.1.0",
  "main": "main.js",
  "author": "me",
  "description": "hello",
  "build": {
    "appId": "com.leon.HelloWorld02",
    "copyright": "LEON",
    "productName": "HelloWorld02",
    "dmg": {
      "window": {
        "x": 100,
        "y": 100,
        "width": 500,
        "height": 300
      }
    },
    "win": {
      "icon": "res/icon.ico"
    }
  },
  "wcjs-prebuilt": {
    "runtime": "electron",
    "runtimeVersion": "v1.4.3",
    "version": "v0.2.7"
  },
  "dependencies": {
    "peerflix": "^0.37.0",
    "wcjs-player": "^6.0.1",
	"webchimera.js": "0.2.7"
  }
}

and My main.js is: 
const electron = require('electron');
const app = electron.app;  
const BrowserWindow = electron.BrowserWindow; 
var mainWindow = null;
app.on('window-all-closed', function() {
  if (process.platform != 'darwin') {
    app.quit();
  }
});
app.on('ready', function() {
  mainWindow = new BrowserWindow({width: 800, height: 600});
  mainWindow.loadURL('file://' + __dirname + '/index.html');
  mainWindow.openDevTools();
  mainWindow.on('closed', function() {
    mainWindow = null;
  });
});

The result is nothing to play.

I check the Developer Tools find next error:
F:\electronWorkSpace\helloword2\node_modules\_wcjs-player@6.0.1@wcjs-player\index.js:632 Uncaught TypeError: Cannot set property 'title' of undefined

then I check the index.js at 632 lines, find it seem like this line :this.vlc.playlist.add(playlist[item].url); not work ok.

now I am not know how to do it, can you help me, thank you.

**Comment by RSATom** [comment]
Is your Electron ia32 or x64?

**Comment by ilvlemon** [comment]
I have resolved it with ： [https://github.com/RSATom/WebChimera.js/wiki/Latest-Electron-and-NW.js-versions-has-compatibility-issue-on-Windows](url)
thank all
