### ISSUE TITLE
Understanding Icons 

### ISSUE THREAD

**Issue by Ciao121** [jaruba/wcjs-player#87]
Hi everyone,
I'm trying to understand how to change a button icon. In the css file I see values as 'E896' for the buttons icons but I cannot find any reference to those codes. Just found out something about Unicode Private Use Areas, but didn't understood at all :)

In short... if I want to change an icon with another one... I do I find the icon code to use?
Thank you!!!

**Comment by Ciao121** [comment]
Think I found the solution.
As ever... I find it right after asking :)
https://github.com/jaruba/WebChimeraPlayer/wiki/Adding-a-Custom-Button-in-the-Toolbar

**Comment by jaruba** [comment]
glad u found it :)
