### ISSUE TITLE
 wcpSettings.wcjs.createPlayer is not a function

### ISSUE THREAD

**Issue by virskor** [jaruba/wcjs-player#88]
wcpSettings.wcjs.createPlayer is not a function

/Users/mac/qiqilive/node_modules/wcjs-player/index.js:1520 Uncaught TypeError: this.find(...).stop is not a function
    at hideUI (/Users/mac/qiqilive/node_modules/wcjs-player/index.js:1520)
    at /Users/mac/qiqilive/node_modules/wcjs-player/index.js:434
hideUI @ /Users/mac/qiqilive/node_modules/wcjs-player/index.js:1520
(anonymous) @ /Users/mac/qiqilive/node_modules/wcjs-player/index.js:434

**Comment by NickersWeb** [comment]
I also got this issue.

**Comment by jaruba** [comment]
This error happens when `Webchimera.js`'s binary is not available or wrong in some way. (for example, the wrong architecture)
