### ISSUE TITLE
toggleAudioTrack function

### ISSUE THREAD

**Issue by kevkha** [jaruba/wcjs-player#9]
In <code>wcjs-player\index.js</code> there is an <code>audioTrack</code> function, how one can toggle between tracks? Do we have a <code>toggleAudioTrack</code> function?

**Comment by jaruba** [comment]
This does not need an internal function, it can be easily done with JS:

    function toggleAudioTrack() {
        if ([-1,0].indexOf(player.audioTrack() > -1) player.audioTrack(1);
        else if (player.audioTrack() +1 < player.audioCount() player.audioTrack(player.audioTrack() +1);
        else player.audioTrack(1);
    }

**Comment by kevkha** [comment]
It works like a champ! Thanks much jaruba!

**Comment by jaruba** [comment]
btw, if your using the latest version of ``wcjs-player``, you can even use ``.notify()`` to announce what audio track your using after you changed it:

    function toggleAudioTrack() {
        if ([-1,0].indexOf(player.audioTrack()) > -1) player.audioTrack(1);
        else if (player.audioTrack() +1 < player.audioCount()) player.audioTrack(player.audioTrack() +1);
        else player.audioTrack(1);
        player.notify("Audio: "+player.audioDesc(player.audioTrack()));
    }

**Comment by kevkha** [comment]
BIG like :) +1:

**Comment by kevkha** [comment]
I tried to prevent <code>player.notify()</code> from showing <code>Audio: undefined</code> when playlist is empty or last playlist item has finished playing. I want to notify only when media is playing or paused state. I see <code>onPlaying</code> and <code>onPaused</code> and <code>onStopped</code> functions but not sure if it's the right direction. What is the best way to achieve this?

**Comment by jaruba** [comment]
> ``.state()`` - get state in human readable format (can be "idle", "opening", "buffering", "playing", "paused", "stopping", "ended" or "error")

> ``.stateInt()`` - get state in int format - Idle = 0, Opening = 1, Buffering = 2, Playing = 3, Paused = 4, Stopping = 5, Ended = 6, Error = 7

so either:

    function toggleAudioTrack() {
        if (["playing","paused"].indexOf(player.state()) > -1) {
            if ([-1,0].indexOf(player.audioTrack()) > -1) player.audioTrack(1);
            else if (player.audioTrack() +1 < player.audioCount()) player.audioTrack(player.audioTrack() +1);
            else player.audioTrack(1);
            player.notify("Audio: "+player.audioDesc(player.audioTrack()));
        }
    }

or even:

    function toggleAudioTrack() {
        if ([3,4].indexOf(player.stateInt()) > -1) {
            if ([-1,0].indexOf(player.audioTrack()) > -1) player.audioTrack(1);
            else if (player.audioTrack() +1 < player.audioCount()) player.audioTrack(player.audioTrack() +1);
            else player.audioTrack(1);
            player.notify("Audio: "+player.audioDesc(player.audioTrack()));
        }
    }

should work, depending on your preference..

**Comment by kevkha** [comment]
Both are very clean and work great!. Thanks again man. Closing for good :)
