### ISSUE TITLE
Use wcjs-player  in reactjs web app

### ISSUE THREAD

**Issue by mas1515** [jaruba/wcjs-player#90]
Hello @jaruba 
can you make demo that i can run 

wcjs-player

in simple  reactjs app ????

i test this   https://github.com/jaruba/node-vlcPlayer-demo
but not work .

i test on electron it is work but in reactjs web application i cant test it
thank you

**Comment by jaruba** [comment]
this issue is a duplicate of: https://github.com/jaruba/wcjs-player/issues/91
